export type WordPair = {
  civilian: string
  undercover: string
}

export type WordPack = {
  id: string
  name: string
  locale: string
  category: string
  pairs: WordPair[]
}

export type SupportedWordLocale = "en" | "my"

export type WordPackLibraryEntry = {
  id: string
  variants: Partial<Record<SupportedWordLocale, Omit<WordPack, "id" | "locale">>>
}

export type WordPackSummary = {
  id: string
  name: string
  category: string
  pairCount: number
  availableLocales: SupportedWordLocale[]
}

function pairs(entries: Array<[string, string]>): WordPair[] {
  return entries.map(([civilian, undercover]) => ({ civilian, undercover }))
}

const classicPairs = pairs([
  ["Coffee", "Tea"],
  ["Beach", "Desert"],
  ["Laptop", "Tablet"],
  ["Pizza", "Burger"],
  ["Thunder", "Lightning"],
  ["Forest", "Jungle"],
  ["Moon", "Sun"],
  ["River", "Lake"],
  ["Train", "Bus"],
  ["Snow", "Rain"],
  ["Window", "Mirror"],
  ["Soap", "Shampoo"],
  ["Pillow", "Blanket"],
  ["Spoon", "Fork"],
  ["Mountain", "Hill"],
  ["Bottle", "Cup"],
  ["Candle", "Lamp"],
  ["Clock", "Calendar"],
  ["Door", "Gate"],
  ["Apple", "Pear"],
  ["Chair", "Stool"],
  ["Shirt", "Jacket"],
  ["Bread", "Toast"],
  ["Ocean", "Sea"],
  ["Car", "Truck"],
  ["Hat", "Cap"],
  ["Ring", "Bracelet"],
  ["Fan", "Air conditioner"],
  ["Book", "Magazine"],
  ["Cake", "Pie"],
  ["Pen", "Pencil"],
  ["Road", "Highway"],
  ["Garden", "Park"],
  ["Bridge", "Tunnel"],
  ["Wallet", "Purse"],
  ["Scarf", "Tie"],
  ["Bell", "Horn"],
  ["Lantern", "Flashlight"],
  ["Socks", "Gloves"],
  ["Rope", "Chain"],
  ["Stone", "Brick"],
  ["Couch", "Bench"],
  ["Village", "Town"],
  ["Castle", "Fort"],
  ["Radio", "Speaker"],
  ["Helmet", "Mask"],
  ["Sugar", "Salt"],
  ["Duck", "Goose"],
  ["Nest", "Hive"],
  ["Seed", "Leaf"],
  ["Feather", "Fur"],
  ["Smile", "Laugh"],
  ["Pocket", "Bag"],
  ["Drawer", "Shelf"],
  ["Plate", "Bowl"],
  ["Map", "Compass"],
  ["Rocket", "Satellite"],
  ["Paint", "Ink"],
  ["Rug", "Mat"],
  ["Notebook", "Journal"],
  ["Boat", "Ship"],
  ["Fire", "Smoke"],
  ["Peach", "Plum"],
  ["Flower", "Rose"],
  ["Gold", "Silver"],
  ["Soup", "Sauce"],
  ["Bridge", "Viaduct"],
  ["Coin", "Token"],
  ["Shell", "Pearl"],
  ["Barn", "Shed"],
  ["Zoo", "Aquarium"],
  ["Ball", "Cube"],
  ["Spring", "Autumn"],
  ["Rabbit", "Squirrel"],
  ["Tiger", "Lion"],
  ["Lamp post", "Traffic light"],
  ["Chef", "Baker"],
  ["Soap bar", "Sponge"],
  ["Fountain", "Pond"],
  ["Tent", "Hammock"],
  ["Key", "Lock"],
  ["Passport", "Ticket"],
  ["Glasses", "Goggles"],
  ["Biscuit", "Cracker"],
  ["Sail", "Anchor"],
  ["Hammer", "Wrench"],
  ["Blank page", "Canvas"],
  ["Curtain", "Blinds"],
  ["Kite", "Balloon"],
  ["Rocket", "Missile"],
  ["Violin", "Cello"],
  ["Chocolate", "Candy"],
  ["Panda", "Koala"],
  ["Cave", "Tunnel"],
  ["Helmet", "Shield"],
  ["Recipe", "Menu"],
  ["Ladder", "Stairs"],
  ["Pineapple", "Coconut"],
  ["Crown", "Tiara"],
  ["Glove", "Mittens"],
])

const cityLifePairs = pairs([
  ["Taxi", "Subway"],
  ["Balcony", "Rooftop"],
  ["Cinema", "Theater"],
  ["Backpack", "Briefcase"],
  ["Market", "Mall"],
  ["Crosswalk", "Intersection"],
  ["Apartment", "Condo"],
  ["Metro", "Tram"],
  ["Cafe", "Bakery"],
  ["Elevator", "Escalator"],
  ["Parking", "Garage"],
  ["Sidewalk", "Alley"],
  ["Office", "Studio"],
  ["Billboard", "Poster"],
  ["Helmet", "Seatbelt"],
  ["Doorman", "Guard"],
  ["Skyscraper", "Tower"],
  ["Food court", "Restaurant"],
  ["Scooter", "Bicycle"],
  ["Plaza", "Square"],
  ["Traffic jam", "Construction"],
  ["Streetlight", "Neon sign"],
  ["Food truck", "Street stall"],
  ["Bus stop", "Train station"],
  ["Condo lobby", "Hotel lobby"],
  ["Escalator", "Moving walkway"],
  ["Suburb", "Downtown"],
  ["Pedestrian", "Cyclist"],
  ["Subway map", "Transit card"],
  ["Mailroom", "Reception desk"],
  ["Bookstore", "Library"],
  ["Gym", "Pool"],
  ["Pharmacy", "Clinic"],
  ["Courier", "Postman"],
  ["Apartment key", "Keycard"],
  ["Window seat", "Aisle seat"],
  ["Street musician", "DJ"],
  ["Vendor", "Cashier"],
  ["Taxi stand", "Bus lane"],
  ["Newsstand", "Kiosk"],
  ["Bridge toll", "Parking meter"],
  ["Fire escape", "Emergency exit"],
  ["Rental bike", "Shared scooter"],
  ["Arcade", "Bowling alley"],
  ["Commuter", "Tourist"],
  ["Loft", "Penthouse"],
  ["Door buzzer", "Intercom"],
  ["Street fair", "Night market"],
  ["Street food", "Food hall"],
  ["Coffee cart", "Snack cart"],
  ["Studio apartment", "Dorm room"],
  ["Security camera", "Doorbell camera"],
  ["Street corner", "Intersection"],
  ["Taxi meter", "Fare gate"],
  ["Receptionist", "Concierge"],
  ["City bus", "Shuttle"],
  ["Rooftop bar", "Lounge"],
  ["Bike lane", "Sidewalk"],
  ["Turnstile", "Barrier"],
  ["Office badge", "Visitor pass"],
  ["Public square", "Courtyard"],
  ["Street mural", "Graffiti"],
  ["Coffee shop", "Tea house"],
  ["Parking lot", "Valet"],
  ["Daycare", "Preschool"],
  ["Neighborhood", "District"],
  ["Apartment hall", "Hotel corridor"],
  ["Trash chute", "Dumpster"],
  ["Delivery app", "Rideshare app"],
  ["Signal", "Crossing guard"],
  ["Skytrain", "Monorail"],
  ["Bus pass", "Train ticket"],
  ["Street cleaner", "Janitor"],
  ["Office cubicle", "Desk pod"],
  ["Plumber", "Electrician"],
  ["Streetlamp", "Headlight"],
  ["Restaurant menu", "QR menu"],
  ["Laundry shop", "Dry cleaner"],
  ["ATM", "Vending machine"],
  ["Food shelf", "Pantry"],
  ["Public bench", "Park bench"],
  ["Ride share", "Carpool"],
  ["Townhouse", "Row house"],
  ["Parking garage", "Basement lot"],
  ["Petrol station", "Charging station"],
  ["Bakery window", "Storefront"],
  ["Mall atrium", "Lobby"],
  ["Commuter train", "Express bus"],
  ["Union", "Guild"],
  ["Gym locker", "Storage locker"],
  ["Power line", "Telephone wire"],
  ["Stairwell", "Hallway"],
  ["Street vendor", "Shopkeeper"],
  ["Apartment rent", "Mortgage"],
  ["Street map", "Tour brochure"],
  ["Reception area", "Waiting room"],
  ["Public fountain", "Memorial"],
  ["Park gate", "Building gate"],
  ["Rooftop garden", "Courtyard garden"],
  ["Crosswalk button", "Doorbell"],
])

const foodDrinkPairs = pairs([
  ["Pancake", "Waffle"],
  ["Noodles", "Pasta"],
  ["Taco", "Burrito"],
  ["Soup", "Stew"],
  ["Donut", "Bagel"],
  ["Cheese", "Butter"],
  ["Ketchup", "Salsa"],
  ["Lemon", "Lime"],
  ["Milkshake", "Smoothie"],
  ["Cookie", "Biscuit"],
  ["Muffin", "Cupcake"],
  ["Shrimp", "Crab"],
  ["Steak", "Ribs"],
  ["Rice", "Quinoa"],
  ["Bacon", "Ham"],
  ["Jam", "Honey"],
  ["Orange juice", "Apple juice"],
  ["Ice cream", "Frozen yogurt"],
  ["Sushi", "Sashimi"],
  ["Popcorn", "Nachos"],
  ["Latte", "Cappuccino"],
  ["Espresso", "Americano"],
  ["Pudding", "Custard"],
  ["Brownie", "Fudge"],
  ["Cereal", "Granola"],
  ["Porridge", "Oatmeal"],
  ["Pita", "Naan"],
  ["Toast", "Bagel"],
  ["Mango", "Peach"],
  ["Cherry", "Berry"],
  ["Watermelon", "Melon"],
  ["Curry", "Soup"],
  ["Dumpling", "Bao"],
  ["Croissant", "Pastry"],
  ["Pretzel", "Breadstick"],
  ["Mayonnaise", "Aioli"],
  ["Mustard", "Relish"],
  ["Hot dog", "Sausage"],
  ["Burger", "Sandwich"],
  ["Omelet", "Scramble"],
  ["Miso", "Broth"],
  ["Tortilla", "Wrap"],
  ["Chili", "Casserole"],
  ["Pickle", "Olive"],
  ["Mocha", "Hot chocolate"],
  ["Syrup", "Molasses"],
  ["Yogurt", "Pudding"],
  ["Cheesecake", "Tart"],
  ["Cup noodle", "Instant soup"],
  ["Lasagna", "Casserole"],
  ["Meatball", "Sausage"],
  ["Ramen", "Udon"],
  ["Gnocchi", "Dumpling"],
  ["Herb", "Spice"],
  ["Mint", "Basil"],
  ["Peanut butter", "Nutella"],
  ["Coconut milk", "Almond milk"],
  ["Sorbet", "Sherbet"],
  ["Jelly", "Jam"],
  ["Wonton", "Ravioli"],
  ["Kimchi", "Pickles"],
  ["Falafel", "Meatball"],
  ["Pesto", "Guacamole"],
  ["Baguette", "Ciabatta"],
  ["Pineapple pizza", "Ham pizza"],
  ["Cider", "Juice"],
  ["Lassi", "Smoothie"],
  ["Coconut water", "Sports drink"],
  ["Soda", "Sparkling water"],
  ["Tonic", "Seltzer"],
  ["Biscotti", "Cookie"],
  ["Macaron", "Meringue"],
  ["Scone", "Biscuit"],
  ["Caramel", "Toffee"],
  ["Hazelnut", "Almond"],
  ["Cashew", "Pistachio"],
  ["Tofu", "Paneer"],
  ["Edamame", "Peas"],
  ["Avocado", "Cucumber"],
  ["Cauliflower", "Broccoli"],
  ["Pumpkin", "Squash"],
  ["Chips", "Fries"],
  ["Kebab", "Skewer"],
  ["Pho", "Ramen"],
  ["Samosa", "Spring roll"],
  ["Croquette", "Nugget"],
  ["Salad", "Slaw"],
  ["Granita", "Sorbet"],
  ["Tea bag", "Coffee filter"],
  ["Margarita", "Daiquiri"],
  ["Cocoa", "Mocha"],
  ["Parfait", "Trifle"],
  ["Sea salt", "Rock salt"],
  ["Egg roll", "Burrito"],
  ["Tiramisu", "Cheesecake"],
  ["Pie crust", "Pastry shell"],
  ["Raisin", "Date"],
  ["Berry jam", "Fruit jelly"],
  ["Churro", "Donut"],
  ["Fried rice", "Paella"],
])

const travelNaturePairs = pairs([
  ["Island", "Peninsula"],
  ["Waterfall", "Fountain"],
  ["Tent", "Cabin"],
  ["Passport", "Visa"],
  ["Suitcase", "Duffel bag"],
  ["Campfire", "Fireplace"],
  ["Glacier", "Iceberg"],
  ["Volcano", "Geyser"],
  ["Trail", "Route"],
  ["Safari", "Zoo"],
  ["Map", "Compass"],
  ["Kayak", "Canoe"],
  ["Cabin crew", "Pilot"],
  ["Airbnb", "Hotel"],
  ["Harbor", "Dock"],
  ["Coral reef", "Seaweed"],
  ["Rainbow", "Sunset"],
  ["Pine tree", "Palm tree"],
  ["Motel", "Hostel"],
  ["Hiking boots", "Snow boots"],
  ["Lagoon", "Bay"],
  ["Canyon", "Valley"],
  ["Ridge", "Cliff"],
  ["Dune", "Hill"],
  ["Pebble", "Shell"],
  ["Harbor cruise", "Ferry"],
  ["Boarding pass", "Ticket"],
  ["Camp site", "Picnic site"],
  ["Peak", "Summit"],
  ["Fog", "Mist"],
  ["Rainforest", "Wetland"],
  ["Cave", "Cavern"],
  ["Meadow", "Field"],
  ["Cabin trail", "Forest path"],
  ["Riverbank", "Shoreline"],
  ["Whale", "Dolphin"],
  ["Seal", "Otter"],
  ["Pond", "Creek"],
  ["Berry bush", "Vine"],
  ["Palm grove", "Forest"],
  ["Water bottle", "Canteen"],
  ["Backpacker", "Camper"],
  ["Sunrise", "Dawn"],
  ["Twilight", "Dusk"],
  ["Desert camp", "Mountain lodge"],
  ["Tide", "Wave"],
  ["Anchor", "Rudder"],
  ["Trailhead", "Checkpoint"],
  ["Snowfall", "Avalanche"],
  ["Wildflower", "Fern"],
  ["Boardwalk", "Pier"],
  ["Travel pillow", "Neck pillow"],
  ["Binoculars", "Telescope"],
  ["Trail mix", "Granola bar"],
  ["Gate", "Terminal"],
  ["Boarding line", "Security line"],
  ["Travel guide", "Map book"],
  ["Beach towel", "Picnic blanket"],
  ["Lifeboat", "Raft"],
  ["Paddles", "Oars"],
  ["Jet lag", "Motion sickness"],
  ["Mountain cabin", "Beach hut"],
  ["Jacket", "Raincoat"],
  ["Horizon", "Skyline"],
  ["Campsite", "Basecamp"],
  ["Lantern", "Camp light"],
  ["Mosquito", "Bee"],
  ["Trail sign", "Road sign"],
  ["Border", "Customs"],
  ["Ski lift", "Cable car"],
  ["Tundra", "Prairie"],
  ["Water bottle", "Thermos"],
  ["Tent peg", "Rope stake"],
  ["Postcard", "Souvenir"],
  ["Museum", "Monument"],
  ["Ruins", "Temple"],
  ["National park", "Botanical garden"],
  ["Rope bridge", "Suspension bridge"],
  ["Bird nest", "Burrow"],
  ["Coconut tree", "Banana tree"],
  ["Hammock", "Beach chair"],
  ["Rain jacket", "Poncho"],
  ["Camp stove", "Grill"],
  ["Picnic basket", "Cooler"],
  ["Lighthouse", "Beacon"],
  ["Turtle", "Tortoise"],
  ["Penguin", "Seagull"],
  ["Cabin window", "Porthole"],
  ["Stargazing", "Birdwatching"],
  ["Orchid", "Lily"],
  ["Moss", "Lichen"],
  ["Dirt road", "Gravel road"],
  ["Trail marker", "Milestone"],
  ["Sea breeze", "Mountain air"],
  ["Tour bus", "Shuttle"],
  ["Wave pool", "Lagoon"],
  ["Camp chair", "Beach stool"],
  ["Travel pouch", "Passport holder"],
  ["Forest cabin", "Lake house"],
  ["River ferry", "Speedboat"],
])

const techMediaPairs = pairs([
  ["Keyboard", "Piano"],
  ["Headphones", "Earbuds"],
  ["Charger", "Adapter"],
  ["Streaming", "Broadcast"],
  ["Podcast", "Radio"],
  ["Camera", "Camcorder"],
  ["Microphone", "Speaker"],
  ["Mouse", "Trackpad"],
  ["Password", "PIN"],
  ["Browser", "Search engine"],
  ["App", "Website"],
  ["Notification", "Alarm"],
  ["Drone", "Helicopter"],
  ["Projector", "Monitor"],
  ["Battery", "Generator"],
  ["Cloud", "Server"],
  ["Screenshot", "Photo"],
  ["Joystick", "Controller"],
  ["Printer", "Scanner"],
  ["Playlist", "Album"],
  ["Tablet", "E-reader"],
  ["Router", "Modem"],
  ["Hard drive", "USB drive"],
  ["Upload", "Download"],
  ["Emoji", "Sticker"],
  ["Avatar", "Profile picture"],
  ["Keyboard shortcut", "Macro"],
  ["Filter", "Lens"],
  ["Tripod", "Stand"],
  ["Live stream", "Video call"],
  ["Text message", "Email"],
  ["Watch", "Smartwatch"],
  ["Console", "PC"],
  ["Laptop stand", "Monitor arm"],
  ["Firewall", "Antivirus"],
  ["Browser tab", "Window"],
  ["Bookmark", "Favorite"],
  ["Search bar", "Address bar"],
  ["Podcast episode", "Radio segment"],
  ["Playlist cover", "Album art"],
  ["VR headset", "Helmet"],
  ["Smart speaker", "Voice assistant"],
  ["Remote", "Gamepad"],
  ["Keyboard backlight", "Screen brightness"],
  ["Data cable", "Power cable"],
  ["Proxy", "VPN"],
  ["User name", "Handle"],
  ["Cloud backup", "Archive"],
  ["Folder", "Directory"],
  ["Cursor", "Pointer"],
  ["Code editor", "Terminal"],
  ["Bug", "Glitch"],
  ["Patch", "Update"],
  ["Beta", "Demo"],
  ["Thumbnail", "Poster"],
  ["Livestream chat", "Comment section"],
  ["Notification badge", "Alert icon"],
  ["Chat bot", "Moderator"],
  ["Wireless mouse", "Bluetooth speaker"],
  ["Touchscreen", "Trackpad"],
  ["Camera roll", "Gallery"],
  ["Headset mic", "Boom mic"],
  ["Streaming app", "Video app"],
  ["Voice memo", "Audio note"],
  ["Ring light", "Desk lamp"],
  ["Charger brick", "Power bank"],
  ["Mirrorless", "DSLR"],
  ["Microchip", "Circuit board"],
  ["Operating system", "Software"],
  ["Software", "Firmware"],
  ["Link", "QR code"],
  ["Screen share", "Projector mode"],
  ["Notification sound", "Ringtone"],
  ["Podcast host", "Radio host"],
  ["Cloud storage", "External drive"],
  ["Edit", "Crop"],
  ["Photo filter", "Video effect"],
  ["USB port", "HDMI port"],
  ["Coding", "Scripting"],
  ["Server rack", "Desktop tower"],
  ["Monitor stand", "Docking station"],
  ["Control room", "Studio"],
  ["Caption", "Subtitle"],
  ["Touch ID", "Face ID"],
  ["Dark mode", "Night light"],
  ["Webcam", "Security camera"],
  ["Micro SD", "SIM card"],
  ["Graphics card", "Processor"],
  ["Lag", "Buffering"],
  ["Battery saver", "Airplane mode"],
  ["Animated GIF", "Short video"],
  ["Noise canceling", "Mute"],
  ["Smart TV", "Projector"],
  ["Firewall", "Password manager"],
  ["QR scanner", "Barcode scanner"],
  ["Video editor", "Photo editor"],
  ["Robot vacuum", "Smart speaker"],
  ["Plug-in", "Extension"],
  ["Status light", "Indicator light"],
  ["Typing sound", "Click sound"],
])

const sportsHobbiesPairs = pairs([
  ["Football", "Rugby"],
  ["Tennis", "Badminton"],
  ["Swimming", "Diving"],
  ["Chess", "Checkers"],
  ["Painting", "Drawing"],
  ["Guitar", "Ukulele"],
  ["Drums", "Tambourine"],
  ["Basketball", "Volleyball"],
  ["Skateboard", "Surfboard"],
  ["Fishing", "Hunting"],
  ["Bowling", "Darts"],
  ["Yoga", "Pilates"],
  ["Origami", "Knitting"],
  ["Karaoke", "Concert"],
  ["Puzzle", "Riddle"],
  ["Snowboard", "Ski"],
  ["Baseball", "Cricket"],
  ["Boxing", "Wrestling"],
  ["Ballet", "Gymnastics"],
  ["Comic book", "Manga"],
  ["Soccer", "Futsal"],
  ["Marathon", "Sprint"],
  ["Cycling", "Running"],
  ["Golf", "Mini golf"],
  ["Dribbling", "Passing"],
  ["Climbing", "Hiking"],
  ["Snorkeling", "Scuba"],
  ["Pottery", "Ceramics"],
  ["Calligraphy", "Lettering"],
  ["Crochet", "Sewing"],
  ["Piano", "Keyboard"],
  ["Flute", "Recorder"],
  ["Violin", "Cello"],
  ["Acting", "Improv"],
  ["Juggling", "Magic"],
  ["Card trick", "Puzzle trick"],
  ["Camping", "Backpacking"],
  ["Birdwatching", "Stargazing"],
  ["Archery", "Darts"],
  ["Karate", "Taekwondo"],
  ["Fencing", "Kendo"],
  ["Board game", "Card game"],
  ["Sudoku", "Crossword"],
  ["Clay", "Slime"],
  ["Photography", "Filming"],
  ["Collecting stamps", "Collecting coins"],
  ["Model train", "RC car"],
  ["RC plane", "Drone"],
  ["Surfing", "Wakeboarding"],
  ["Roller skating", "Ice skating"],
  ["Long jump", "High jump"],
  ["Shot put", "Discus"],
  ["Table tennis", "Air hockey"],
  ["Billiards", "Snooker"],
  ["Choir", "Band"],
  ["Songwriting", "Poetry"],
  ["Reading club", "Debate club"],
  ["Cosplay", "Costume design"],
  ["Baking", "Cooking"],
  ["Fishing rod", "Net"],
  ["Camping stove", "Portable grill"],
  ["Kite flying", "Paper plane"],
  ["Puzzle cube", "Jigsaw"],
  ["Base jump", "Bungee jump"],
  ["Bodybuilding", "Powerlifting"],
  ["Bench press", "Deadlift"],
  ["Ice hockey", "Field hockey"],
  ["Handball", "Netball"],
  ["Rowing", "Canoeing"],
  ["Sailing", "Windsurfing"],
  ["Horse riding", "Camel riding"],
  ["Dog agility", "Horse jumping"],
  ["Magic card", "Playing card"],
  ["Lego build", "Model kit"],
  ["Embroidery", "Cross-stitch"],
  ["Whittling", "Wood carving"],
  ["Hip hop", "Breakdance"],
  ["Salsa", "Tango"],
  ["Meditation", "Breathing exercise"],
  ["Field trip", "Camping trip"],
  ["Film club", "Drama club"],
  ["Trivia night", "Quiz show"],
  ["Escape room", "Treasure hunt"],
  ["Treasure map", "Clue sheet"],
  ["Sledding", "Tubing"],
  ["Parkour", "Gymnastics"],
  ["Miniature painting", "Sketching"],
  ["Aquarium keeping", "Gardening"],
  ["Flower arranging", "Table setting"],
  ["Snow angel", "Sand angel"],
  ["Ping pong paddle", "Tennis racket"],
  ["Goalkeeper", "Defender"],
  ["Referee", "Coach"],
  ["Scoreboard", "Stopwatch"],
  ["Team captain", "Club president"],
  ["Cheerleading", "Dance team"],
  ["Costume", "Uniform"],
  ["Croquet", "Bocce"],
  ["Foam roller", "Yoga mat"],
  ["Sketchbook", "Canvas pad"],
])

const schoolWorkPairs = pairs([
  ["Teacher", "Professor"],
  ["Homework", "Quiz"],
  ["Notebook", "Textbook"],
  ["Stapler", "Paperclip"],
  ["Whiteboard", "Blackboard"],
  ["Intern", "Assistant"],
  ["Meeting", "Workshop"],
  ["Resume", "Portfolio"],
  ["Deadline", "Schedule"],
  ["Presentation", "Lecture"],
  ["Manager", "Supervisor"],
  ["Uniform", "Dress code"],
  ["Calculator", "Abacus"],
  ["Locker", "Drawer"],
  ["Bell", "Whistle"],
  ["Marker", "Crayon"],
  ["Clipboard", "Folder"],
  ["Exam", "Interview"],
  ["Lab", "Workshop"],
  ["Certificate", "Diploma"],
  ["Principal", "Dean"],
  ["Classroom", "Lecture hall"],
  ["Desk", "Cubicle"],
  ["Hall pass", "Visitor pass"],
  ["Essay", "Report"],
  ["Syllabus", "Agenda"],
  ["Lesson", "Tutorial"],
  ["Mentor", "Tutor"],
  ["Internship", "Apprenticeship"],
  ["Payroll", "Invoice"],
  ["Memo", "Notice"],
  ["Orientation", "Onboarding"],
  ["Name tag", "Badge"],
  ["Attendance", "Timesheet"],
  ["Shift", "Schedule"],
  ["Reception", "Front desk"],
  ["Staff room", "Break room"],
  ["Locker room", "Storage room"],
  ["Project", "Assignment"],
  ["Planner", "Calendar"],
  ["Notebook paper", "Sticky note"],
  ["Photocopier", "Printer"],
  ["Projector screen", "Whiteboard"],
  ["Brainstorm", "Discussion"],
  ["Manager meeting", "Team huddle"],
  ["Payroll", "Budget"],
  ["Grade", "Score"],
  ["Uniform shirt", "Name badge"],
  ["Spreadsheet", "Report"],
  ["Desk lamp", "Monitor light"],
  ["Calculator app", "Spreadsheet"],
  ["Signature", "Initials"],
  ["Research", "Survey"],
  ["Experiment", "Observation"],
  ["Assignment sheet", "Rubric"],
  ["Group project", "Case study"],
  ["Attendance sheet", "Roster"],
  ["Career fair", "Open house"],
  ["Training", "Seminar"],
  ["Orientation week", "Exam week"],
  ["Office chair", "Desk chair"],
  ["Cubicle wall", "Whiteboard wall"],
  ["Textbook chapter", "Workbook page"],
  ["Planner app", "Calendar app"],
  ["Memo pad", "Notebook"],
  ["Report card", "Transcript"],
  ["Reference letter", "Certificate"],
  ["Phone interview", "Video interview"],
  ["Course", "Class"],
  ["Major", "Minor"],
  ["Field trip", "Lab visit"],
  ["Faculty", "Department"],
  ["Notebook tab", "Binder tab"],
  ["Paper tray", "Mailbox"],
  ["Janitor closet", "Supply room"],
  ["Cafeteria", "Food court"],
  ["Auditorium", "Gymnasium"],
  ["Semester", "Quarter"],
  ["Payroll stub", "Receipt"],
  ["Company policy", "Rulebook"],
  ["Team lead", "Supervisor"],
  ["School bus", "Shuttle"],
  ["Class photo", "ID photo"],
  ["Poster board", "Tri-fold board"],
  ["Science fair", "Book fair"],
  ["Craft paper", "Printer paper"],
  ["Timer", "Stopwatch"],
  ["Reception call", "Help desk ticket"],
  ["Checklist", "Worksheet"],
  ["Q and A", "Discussion"],
  ["Revision", "Draft"],
  ["Coach", "Advisor"],
  ["Shift manager", "Floor manager"],
  ["Office lunch", "School lunch"],
  ["Transcript", "Resume"],
  ["Planner sticker", "Sticky note"],
  ["Homework folder", "Lunch box"],
  ["Company email", "Memo"],
  ["Desk organizer", "Supply tray"],
  ["Workshop room", "Conference room"],
])

const homeDailyPairs = pairs([
  ["Sofa", "Armchair"],
  ["Fridge", "Freezer"],
  ["Toothbrush", "Razor"],
  ["Laundry", "Dishes"],
  ["Broom", "Mop"],
  ["Curtain", "Blinds"],
  ["Pan", "Pot"],
  ["Closet", "Wardrobe"],
  ["Alarm clock", "Timer"],
  ["Toaster", "Microwave"],
  ["Sink", "Bathtub"],
  ["Vacuum", "Leaf blower"],
  ["Hanger", "Hook"],
  ["Rug", "Carpet"],
  ["Nightstand", "Desk"],
  ["Shower", "Faucet"],
  ["Soap dispenser", "Lotion bottle"],
  ["Couch", "Bench"],
  ["Kettle", "Teapot"],
  ["Mailbox", "Package box"],
  ["Dish rack", "Drying rack"],
  ["Laundry basket", "Storage bin"],
  ["Pillowcase", "Bedsheet"],
  ["Mattress", "Futon"],
  ["Blanket", "Comforter"],
  ["Curtain rod", "Shelf bracket"],
  ["Remote", "Switch"],
  ["Ceiling fan", "Table fan"],
  ["Doormat", "Bath mat"],
  ["Door handle", "Cabinet knob"],
  ["Stove", "Oven"],
  ["Frying pan", "Saucepan"],
  ["Knife", "Scissors"],
  ["Plate rack", "Cup shelf"],
  ["Dining table", "Coffee table"],
  ["Laundry detergent", "Fabric softener"],
  ["Iron", "Steamer"],
  ["Basket", "Bucket"],
  ["Dustpan", "Brush"],
  ["Shampoo bottle", "Conditioner bottle"],
  ["Toilet paper", "Paper towel"],
  ["Bath towel", "Hand towel"],
  ["Mug", "Glass"],
  ["Blender", "Mixer"],
  ["Rice cooker", "Slow cooker"],
  ["Dish sponge", "Scrub brush"],
  ["Laundry room", "Pantry"],
  ["Trash can", "Recycling bin"],
  ["Bed frame", "Headboard"],
  ["Mirror cabinet", "Medicine cabinet"],
  ["Shoe rack", "Coat rack"],
  ["Vacuum bag", "Trash bag"],
  ["Cushion", "Pillow"],
  ["Shelf", "Cabinet"],
  ["Desk lamp", "Floor lamp"],
  ["Light switch", "Doorbell"],
  ["Freezer tray", "Ice bucket"],
  ["Soap bar", "Shower gel"],
  ["Washing machine", "Dryer"],
  ["Laundry line", "Clothes rack"],
  ["Bathroom sink", "Kitchen sink"],
  ["Water jug", "Pitcher"],
  ["Dishwasher", "Drying rack"],
  ["Apron", "Oven mitt"],
  ["Clock radio", "Alarm clock"],
  ["Tea towel", "Napkin"],
  ["Storage box", "Drawer organizer"],
  ["Vacuum hose", "Garden hose"],
  ["Wall shelf", "Bookcase"],
  ["Bedroom", "Guest room"],
  ["Dining chair", "Bar stool"],
  ["Soap tray", "Toothbrush holder"],
  ["Tissue box", "Wipes box"],
  ["Window sill", "Door frame"],
  ["Pan lid", "Pot lid"],
  ["Water filter", "Kettle"],
  ["Bedside lamp", "Hall lamp"],
  ["Bathrobe", "Pajamas"],
  ["Laundry soap", "Dish soap"],
  ["Cleaning spray", "Air freshener"],
  ["Cupboard", "Pantry"],
  ["Toilet brush", "Bottle brush"],
  ["Mixer bowl", "Salad bowl"],
  ["Spice rack", "Knife block"],
  ["Linen closet", "Pantry closet"],
  ["House key", "Mailbox key"],
  ["Pet bed", "Baby crib"],
  ["Laundry hamper", "Toy basket"],
  ["Blanket ladder", "Towel rack"],
  ["Watering can", "Spray bottle"],
  ["Drain", "Plug"],
  ["Rolling pin", "Whisk"],
  ["Measuring cup", "Measuring spoon"],
  ["Clock battery", "Remote battery"],
  ["Shower curtain", "Glass door"],
  ["Paper lantern", "Ceiling lamp"],
  ["Laundry clips", "Hangers"],
  ["Kitchen timer", "Egg timer"],
  ["Porch", "Patio"],
  ["Entryway", "Hallway"],
])

const hardModePairs = pairs([
  ["Violin", "Viola"],
  ["Lizard", "Gecko"],
  ["Mansion", "Villa"],
  ["Journal", "Diary"],
  ["Statue", "Sculpture"],
  ["Lantern", "Torch"],
  ["Harp", "Lyre"],
  ["Canal", "River"],
  ["Meteor", "Comet"],
  ["Ink", "Paint"],
  ["Sapphire", "Ruby"],
  ["Flute", "Clarinet"],
  ["Mushroom", "Truffle"],
  ["Balustrade", "Railing"],
  ["Pavilion", "Gazebo"],
  ["Compass", "Sextant"],
  ["Dolphin", "Porpoise"],
  ["Velvet", "Silk"],
  ["Helmet", "Hard hat"],
  ["Manuscript", "Novel"],
  ["Locket", "Pendant"],
  ["Aisle", "Corridor"],
  ["Chasm", "Canyon"],
  ["Harpsichord", "Piano"],
  ["Monastery", "Abbey"],
  ["Falcon", "Hawk"],
  ["Granite", "Marble"],
  ["Tapestry", "Mural"],
  ["Parchment", "Canvas"],
  ["Spear", "Javelin"],
  ["Scepter", "Crown"],
  ["Harbor", "Marina"],
  ["Summit", "Peak"],
  ["Echo", "Reverb"],
  ["Orbit", "Trajectory"],
  ["Crescent", "Arc"],
  ["Portrait", "Bust"],
  ["Quill", "Nib"],
  ["Caravan", "Convoy"],
  ["Silhouette", "Outline"],
  ["Crescendo", "Climax"],
  ["Compass rose", "Map legend"],
  ["Parable", "Fable"],
  ["Vault", "Crypt"],
  ["Monolith", "Obelisk"],
  ["Harpoon", "Spear"],
  ["Orchid", "Iris"],
  ["Marsh", "Bog"],
  ["Granary", "Silo"],
  ["Atrium", "Foyer"],
  ["Fresco", "Mosaic"],
  ["Loom", "Spindle"],
  ["Tundra", "Steppe"],
  ["Pond", "Lagoon"],
  ["Ledger", "Register"],
  ["Medallion", "Coin"],
  ["Raven", "Crow"],
  ["Cloak", "Cape"],
  ["Pebble", "Gravel"],
  ["Archipelago", "Peninsula"],
  ["Spire", "Turret"],
  ["Harbor master", "Captain"],
  ["Hearth", "Mantel"],
  ["Lanai", "Balcony"],
  ["Crater", "Basin"],
  ["Banyan", "Oak"],
  ["Fjord", "Bay"],
  ["Lattice", "Trellis"],
  ["Anvil", "Forge"],
  ["Stanza", "Verse"],
  ["Scribe", "Author"],
  ["Horizon", "Vista"],
  ["Pillar", "Column"],
  ["Glade", "Grove"],
  ["Cairn", "Monument"],
  ["Thicket", "Hedge"],
  ["Vessel", "Flask"],
  ["Ember", "Ash"],
  ["Cask", "Barrel"],
  ["Reef", "Shoal"],
  ["Coffer", "Chest"],
  ["Minstrel", "Bard"],
  ["Skiff", "Dinghy"],
  ["Easel", "Stand"],
  ["Hilt", "Handle"],
  ["Relic", "Artifact"],
  ["Spiral", "Helix"],
  ["Acorn", "Chestnut"],
  ["Scroll", "Script"],
  ["Mariner", "Sailor"],
  ["Aperture", "Lens"],
  ["Satchel", "Tote"],
  ["Tome", "Volume"],
  ["Galleon", "Frigate"],
  ["Belfry", "Bell tower"],
  ["Rivulet", "Stream"],
  ["Carafe", "Decanter"],
  ["Etching", "Engraving"],
  ["Citadel", "Fortress"],
  ["Reticle", "Crosshair"],
])

const familyFunPairs = pairs([
  ["Cat", "Dog"],
  ["Cake", "Pie"],
  ["Balloon", "Bubble"],
  ["Duck", "Goose"],
  ["Rainbow", "Cloud"],
  ["Robot", "Toy car"],
  ["Pirate", "Ninja"],
  ["Cookie", "Brownie"],
  ["Castle", "Palace"],
  ["Teddy bear", "Doll"],
  ["Parrot", "Peacock"],
  ["Spaceship", "Rocket"],
  ["Lemonade", "Soda"],
  ["Treasure", "Crown"],
  ["Crayon", "Marker"],
  ["Swing", "Slide"],
  ["Puppy", "Kitten"],
  ["Pajamas", "Slippers"],
  ["Dragon", "Dinosaur"],
  ["Snowman", "Sandcastle"],
  ["Princess", "Fairy"],
  ["Knight", "Wizard"],
  ["Jellyfish", "Starfish"],
  ["Popsicle", "Ice cream"],
  ["Birthday", "Holiday"],
  ["Puzzle", "Blocks"],
  ["Ball pit", "Trampoline"],
  ["Rabbit", "Bunny"],
  ["Monkey", "Gorilla"],
  ["Toy train", "Toy plane"],
  ["Fire truck", "Ambulance"],
  ["Rainbow cake", "Cupcake"],
  ["Sticker", "Stamp"],
  ["Hopscotch", "Tag"],
  ["Treasure map", "Storybook"],
  ["Pencil case", "Backpack"],
  ["Apple juice", "Orange juice"],
  ["Dinosaur", "Dragon"],
  ["Unicorn", "Pegasus"],
  ["Bathtub", "Pool"],
  ["Castle tower", "Treehouse"],
  ["Toy drum", "Toy piano"],
  ["Goldfish", "Turtle"],
  ["Campfire", "Picnic"],
  ["Rain boots", "Snow boots"],
  ["Bunny ears", "Cat ears"],
  ["Playdough", "Clay"],
  ["Coloring book", "Comic book"],
  ["Marble", "Dice"],
  ["Lollipop", "Gummy"],
  ["Treasure chest", "Toy box"],
  ["Kite", "Paper plane"],
  ["Daisy", "Sunflower"],
  ["Parade", "Festival"],
  ["Storybook", "Fairy tale"],
  ["Cookie jar", "Candy jar"],
  ["Pond", "Puddle"],
  ["Bicycle", "Scooter"],
  ["Toy soldier", "Action figure"],
  ["Water gun", "Bubble wand"],
  ["Jungle gym", "Monkey bars"],
  ["Hide and seek", "Tag"],
  ["Ring toss", "Bowling"],
  ["Puppet", "Plushie"],
  ["Pony", "Horse"],
  ["Duck pond", "Fish pond"],
  ["Moon", "Star"],
  ["Birthday hat", "Party mask"],
  ["Crown", "Tiara"],
  ["Cookie cutter", "Rolling pin"],
  ["Bedtime story", "Lullaby"],
  ["Blanket fort", "Treehouse"],
  ["Treasure hunt", "Scavenger hunt"],
  ["Toy chef", "Toy doctor"],
  ["Tugboat", "Sailboat"],
  ["Beach ball", "Soccer ball"],
  ["Spring roll", "Rice ball"],
  ["Piggy bank", "Treasure chest"],
  ["Shark", "Whale"],
  ["Cloud", "Fog"],
  ["Magic wand", "Sword"],
  ["Knight helmet", "Pirate hat"],
  ["Rubber duck", "Toy boat"],
  ["Toy kitchen", "Toy store"],
  ["Color pencil", "Crayon"],
  ["Fruit snack", "Granola bar"],
  ["Popsicle stick", "Straw"],
  ["Dress-up", "Costume party"],
  ["Snowflake", "Raindrop"],
  ["Playhouse", "Clubhouse"],
  ["Bunny hop", "Frog jump"],
  ["Firefly", "Butterfly"],
  ["Pine cone", "Acorn"],
  ["Cracker", "Pretzel"],
  ["Sled", "Wagon"],
  ["Toy rocket", "Toy spaceship"],
  ["Beach bucket", "Watering can"],
  ["Toy phone", "Toy camera"],
  ["Rainbow slide", "Ferris wheel"],
  ["Toy shovel", "Toy rake"],
])

const myanmarClassicPairs = pairs([
  ["လက်ဖက်ရည်", "ကော်ဖီ"],
  ["ထမင်း", "ခေါက်ဆွဲ"],
  ["မိုး", "နှင်း"],
  ["နေ", "လ"],
  ["မြစ်", "ချောင်း"],
  ["တောင်", "ကုန်း"],
  ["ပင်လယ်", "အင်း"],
  ["သစ်တော", "တော"],
  ["ပန်း", "ရွက်"],
  ["သစ်သီး", "ဟင်းသီးဟင်းရွက်"],
  ["ပန်းသီး", "သစ်တော်သီး"],
  ["ငှက်ပျောသီး", "သရက်သီး"],
  ["လိမ္မော်သီး", "သံပုရာသီး"],
  ["စတော်ဘယ်ရီ", "ချယ်ရီ"],
  ["ဖရဲသီး", "သခွားမွှေး"],
  ["စပျစ်သီး", "နာနတ်သီး"],
  ["မုန့်", "ကိတ်"],
  ["ပေါင်မုန့်", "ပေါင်မုန့်ကြော်"],
  ["ကြက်ဥ", "ဘဲဥ"],
  ["ကြက်သား", "ဝက်သား"],
  ["ငါး", "ပုစွန်"],
  ["ဟင်းချို", "ဟင်းရည်"],
  ["ဆား", "သကြား"],
  ["ပဲ", "ဆန်"],
  ["ဖန်ခွက်", "ခွက်"],
  ["ပန်းကန်", "ပန်းကန်လုံး"],
  ["ဇွန်း", "ခက်ရင်း"],
  ["ဓား", "ကတ်ကြေး"],
  ["အိုး", "ဒယ်အိုး"],
  ["မီးဖို", "မိုက်ခရိုဝေ့ဗ်"],
  ["ရေခဲသေတ္တာ", "ရေခဲခန်း"],
  ["စားပွဲ", "ကုလားထိုင်"],
  ["ဆိုဖာ", "ခုံတန်း"],
  ["အိပ်ယာ", "မွေ့ရာ"],
  ["ခေါင်းအုံး", "စောင်"],
  ["ပြတင်းပေါက်", "မှန်"],
  ["တံခါး", "ဂိတ်"],
  ["မီးအိမ်", "မီးပုံး"],
  ["နာရီ", "ပြက္ခဒိန်"],
  ["စာအုပ်", "မဂ္ဂဇင်း"],
  ["ဘောပင်", "ခဲတံ"],
  ["မှတ်စုစာအုပ်", "ဒိုင်ယာရီ"],
  ["မြေပုံ", "ကွန်ပတ်"],
  ["ဖုန်း", "တက်ဘလက်"],
  ["လက်တော့ပ်", "ကွန်ပျူတာ"],
  ["တီဗီ", "ရေဒီယို"],
  ["နားကြပ်", "စပီကာ"],
  ["ကင်မရာ", "မိုဘိုင်းဖုန်း"],
  ["ကား", "ဘတ်စ်ကား"],
  ["ရထား", "လေယာဉ်"],
  ["စက်ဘီး", "ဆိုင်ကယ်"],
  ["သင်္ဘော", "လှေ"],
  ["လမ်း", "အဝေးပြေးလမ်း"],
  ["တံတား", "ဂူပေါက်လမ်း"],
  ["စျေး", "ကုန်တိုက်"],
  ["ဆိုင်", "ဈေးဆိုင်"],
  ["ကျောင်း", "တက္ကသိုလ်"],
  ["အိမ်", "တိုက်ခန်း"],
  ["အခန်း", "ဧည့်ခန်း"],
  ["မီးဖိုချောင်", "ရေချိုးခန်း"],
  ["ဥယျာဉ်", "ပန်းခြံ"],
  ["ကမ်းခြေ", "သဲကန္တာရ"],
  ["မိုးတိမ်", "မြူ"],
  ["လေ", "မုန်တိုင်း"],
  ["မီး", "မီးခိုး"],
  ["ကျောက်", "အုတ်"],
  ["ရွှေ", "ငွေ"],
  ["လက်စွပ်", "လက်ကောက်"],
  ["ဦးထုပ်", "ဦးခေါင်းစွပ်"],
  ["အင်္ကျီ", "ဂျာကင်"],
  ["ဘောင်းဘီ", "စကတ်"],
  ["ခြေအိတ်", "လက်အိတ်"],
  ["ဖိနပ်", "စလစ်ပါ"],
  ["အိတ်", "ပိုက်ဆံအိတ်"],
  ["သော့", "သော့ခလောက်"],
  ["လက်မှတ်", "ပတ်စ်ပို့"],
  ["ဆရာ", "ကျောင်းသား"],
  ["ဆရာဝန်", "သူနာပြု"],
  ["ရဲ", "လုံခြုံရေး"],
  ["မုန့်ဖုတ်သမား", "စားဖိုမှူး"],
  ["ကြောင်", "ခွေး"],
  ["ငှက်", "ကြက်"],
  ["ကျား", "ခြင်္သေ့"],
  ["ဆင်", "မြင်း"],
  ["မျောက်", "ဂေါ်ရီလာ"],
  ["ငါးမန်း", "ဝေလငါး"],
  ["လိပ်", "ဖား"],
  ["ပျား", "လိပ်ပြာ"],
  ["ပင့်ကူ", "ပိုးဟပ်"],
  ["နှင်းဆီ", "စံပယ်"],
  ["ကော်ဖီဆိုင်", "မုန့်ဆိုင်"],
  ["ဖုန်းအက်ပ်", "ဝက်ဘ်ဆိုက်"],
  ["ဓာတ်ပုံ", "ဗီဒီယို"],
  ["ဂိမ်း", "ရုပ်ရှင်"],
  ["သီချင်း", "တေးဂီတ"],
  ["ဘောလုံး", "ဘတ်စကက်ဘော"],
  ["တင်းနစ်", "ကြက်တောင်"],
  ["ကဒ်", "ဒိုင်စ်"],
  ["ပွဲတော်", "ချီတက်ပွဲ"],
  ["မိုးကာ", "ထီး"],
])

const myanmarCityLifePairs = pairs([
  ["တက္ကစီ", "မြေအောက်ရထား"],
  ["ဘော်လကနီ", "ခေါင်မိုးပေါ်နေရာ"],
  ["ရုပ်ရှင်ရုံ", "ဇာတ်ရုံ"],
  ["ကျောပိုးအိတ်", "လက်ဆွဲအိတ်"],
  ["ဈေး", "ကုန်တိုက်"],
  ["လမ်းကူးနေရာ", "လမ်းဆုံ"],
  ["တိုက်ခန်း", "ကွန်ဒို"],
  ["မက်ထရို", "လမ်းမီးရထား"],
  ["ကဖေး", "မုန့်ဆိုင်"],
  ["ဓာတ်လှေကား", "စက်လှေကား"],
  ["ကားရပ်ရန်နေရာ", "ဂိုဒေါင်ကားရပ်"],
  ["လမ်းဘေးလျှောက်လမ်း", "လမ်းကြား"],
  ["ရုံးခန်း", "စတူဒီယို"],
  ["ကြော်ငြာဘုတ်", "ပိုစတာ"],
  ["ဟယ်လ်မက်", "ခါးပတ်"],
  ["တံခါးစောင့်", "လုံခြုံရေး"],
  ["မိုးမျှော်တိုက်", "မျှော်စင်"],
  ["စားသောက်ဆိုင်ခန်းမ", "စားသောက်ဆိုင်"],
  ["လျှပ်စစ်ဆိုင်ကယ်", "စက်ဘီး"],
  ["ပလာဇာ", "ရင်ပြင်"],
  ["ယာဉ်ကြောပိတ်ဆို့", "ဆောက်လုပ်ရေးနေရာ"],
  ["လမ်းမီး", "နီယွန်မီးဆိုင်း"],
  ["အစားအသောက်ကား", "လမ်းဘေးဆိုင်"],
  ["ဘတ်စ်ကားမှတ်တိုင်", "ရထားဘူတာ"],
  ["ကွန်ဒိုဧည့်ခန်း", "ဟိုတယ်ဧည့်ခန်း"],
  ["စက်လှေကား", "ရွေ့လျားလမ်း"],
  ["မြို့နယ်အစွန်", "မြို့လယ်"],
  ["လမ်းလျှောက်သူ", "စက်ဘီးစီးသူ"],
  ["မြေအောက်ရထားမြေပုံ", "သယ်ယူပို့ဆောင်ရေးကတ်"],
  ["စာပို့ခန်း", "ဧည့်ကြိုကောင်တာ"],
  ["စာအုပ်ဆိုင်", "စာကြည့်တိုက်"],
  ["အားကစားရုံ", "ရေကူးကန်"],
  ["ဆေးဆိုင်", "ဆေးခန်း"],
  ["ပို့ဆောင်သူ", "စာပို့သမား"],
  ["တိုက်ခန်းသော့", "ကီးကတ်"],
  ["ပြတင်းပေါက်ဘက်ထိုင်ခုံ", "လမ်းကြားဘက်ထိုင်ခုံ"],
  ["လမ်းဘေးတေးဂီတသမား", "ဒီဂျေ"],
  ["ရောင်းသူ", "ငွေကောက်သူ"],
  ["တက္ကစီရပ်ရန်နေရာ", "ဘတ်စ်ကားလမ်းကြော"],
  ["သတင်းစာစင်", "ကီယို့စ်"],
  ["တံတားကြေး", "ကားရပ်မီတာ"],
  ["မီးဘေးထွက်ပေါက်လှေကား", "အရေးပေါ်ထွက်ပေါက်"],
  ["ငှားစက်ဘီး", "မျှဝေစကူတာ"],
  ["အာကိတ်ဂိမ်းခန်း", "ဘိုးလင်းခန်း"],
  ["အလုပ်သွားသူ", "ခရီးသွားသူ"],
  ["လော့ဖ်တိုက်ခန်း", "ပင့်ထောင့်တိုက်ခန်း"],
  ["တံခါးခေါ်ခလုတ်", "အင်တာကွမ်း"],
  ["လမ်းဘေးပွဲတော်", "ညဈေး"],
  ["လမ်းဘေးအစားအစာ", "စားသောက်ခန်းမ"],
  ["ကော်ဖီတွန်းလှည်း", "မုန့်တွန်းလှည်း"],
  ["စတူဒီယိုတိုက်ခန်း", "အဆောင်ခန်း"],
  ["လုံခြုံရေးကင်မရာ", "တံခါးခေါ်ကင်မရာ"],
  ["လမ်းထောင့်", "လမ်းဆုံ"],
  ["တက္ကစီမီတာ", "ဝင်ပေါက်ဂိတ်"],
  ["ဧည့်ကြို", "ကွန်စီယာ့"],
  ["မြို့ပတ်ဘတ်စ်ကား", "ရှပ်တယ်ကား"],
  ["ခေါင်မိုးပေါ်ဘား", "လောင်းချ်ခန်း"],
  ["စက်ဘီးလမ်းကြော", "လမ်းဘေးလျှောက်လမ်း"],
  ["အဝင်လှည့်ဂိတ်", "အတားအဆီးဘား"],
  ["ရုံးကတ်", "ဧည့်သည်ကတ်"],
  ["အများပြည်သူရင်ပြင်", "ဝင်းအတွင်းခြံဝန်း"],
  ["လမ်းဘေးပန်းချီ", "ဂရပ်ဖီတီ"],
  ["ကော်ဖီဆိုင်", "လက်ဖက်ရည်ဆိုင်"],
  ["ကားရပ်ကွင်း", "ကားရပ်ဝန်ဆောင်မှု"],
  ["ကလေးထိန်းဌာန", "ကြိုတင်ကျောင်း"],
  ["ရပ်ကွက်", "ခရိုင်"],
  ["တိုက်ခန်းလမ်းကြောင်း", "ဟိုတယ်လျှောက်လမ်း"],
  ["အမှိုက်ပစ်ခေါင်းပေါက်", "အမှိုက်ပုံးကြီး"],
  ["ပို့ဆောင်ရေးအက်ပ်", "ယာဉ်မျှဝေအက်ပ်"],
  ["မီးပွိုင့်", "လမ်းကူးစောင့်"],
  ["မြင့်မားရထား", "မိုနိုရထား"],
  ["ဘတ်စ်ကားကတ်", "ရထားလက်မှတ်"],
  ["လမ်းသန့်ရှင်းရေးသမား", "သန့်ရှင်းရေးဝန်ထမ်း"],
  ["ရုံးအကာခန်း", "စားပွဲခုံငယ်"],
  ["ရေပိုက်သမား", "လျှပ်စစ်သမား"],
  ["လမ်းမီးတိုင်", "ကားမီး"],
  ["စားသောက်ဆိုင်မီနူး", "QR မီနူး"],
  ["အဝတ်လျှော်ဆိုင်", "ဒရိုင်ကလင်းဆိုင်"],
  ["ATM စက်", "အလိုအလျောက်ရောင်းစက်"],
  ["အစားအစာစင်", "သိုလှောင်ခန်း"],
  ["အများသုံးထိုင်ခုံ", "ပန်းခြံထိုင်ခုံ"],
  ["ကားမျှဝေစီးခြင်း", "ကားပူးပေါင်းစီးခြင်း"],
  ["အတန်းလိုက်အိမ်", "တစ်ဆက်တည်းအိမ်"],
  ["အထပ်လိုက်ကားရပ်ခန်း", "မြေအောက်ကားရပ်ခန်း"],
  ["ဆီဆိုင်", "လျှပ်စစ်အားသွင်းစခန်း"],
  ["မုန့်ဆိုင်မျက်နှာစာ", "ဆိုင်မျက်နှာစာ"],
  ["ကုန်တိုက်အလယ်ခန်း", "ဧည့်ခန်းမ"],
  ["ခရီးသွားရထား", "အမြန်ဘတ်စ်ကား"],
  ["အလုပ်သမားသမဂ္ဂ", "အဖွဲ့အစည်း"],
  ["အားကစားရုံလော့ကာ", "သိုလှောင်လော့ကာ"],
  ["မီးအားကြိုး", "ဖုန်းကြိုး"],
  ["လှေကားခန်း", "လျှောက်လမ်း"],
  ["လမ်းဘေးရောင်းသူ", "ဆိုင်ရှင်"],
  ["အိမ်လခ", "အိမ်ချေးငွေ"],
  ["မြို့မြေပုံ", "ခရီးသွားလမ်းညွှန်စာအုပ်"],
  ["ဧည့်ကြိုနေရာ", "စောင့်ဆိုင်းခန်း"],
  ["အများသုံးရေပန်း", "အမှတ်တရကျောက်တိုင်"],
  ["ပန်းခြံဂိတ်", "အဆောက်အဦဂိတ်"],
  ["ခေါင်မိုးပေါ်ဥယျာဉ်", "ဝင်းအတွင်းဥယျာဉ်"],
  ["လမ်းကူးခလုတ်", "တံခါးခေါ်ခလုတ်"],
])

const myanmarFoodDrinkPairs = pairs([
  ["မုန့်ပြား", "ဝါဖယ်"],
  ["ခေါက်ဆွဲ", "ပါစတာ"],
  ["တာကို", "ဘူရီတို"],
  ["ဟင်းချို", "စတူး"],
  ["ဒိုးနပ်", "ဘေးဂယ်"],
  ["ချိစ်", "ထောပတ်"],
  ["ခရမ်းချဉ်သီးဆော့စ်", "ဆော်လ်ဆာ"],
  ["သံပုရာသီး", "လိမ္မော်သီးစိမ်း"],
  ["မစ်လ်ရှိတ်", "စမူးသီး"],
  ["ကွတ်ကီး", "ဘစ်စကစ်"],
  ["မဖ်ဖင်", "ခွက်ကိတ်"],
  ["ပုစွန်", "ဂဏန်း"],
  ["အသားကင်", "နံရိုးကင်"],
  ["ဆန်", "ကွီနိုအာ"],
  ["ဘေကွန်", "ဟမ်"],
  ["ယို", "ပျားရည်"],
  ["လိမ္မော်ရည်", "ပန်းသီးရည်"],
  ["ရေခဲမုန့်", "ဖရိုဇင်ယိုဂတ်"],
  ["ဆူရှီ", "ဆာရှီမီ"],
  ["ပေါက်ပေါက်ဆန်", "နာချို"],
  ["လာတေး", "ကပ်ပူချီနို"],
  ["အက်စ်ပရက်ဆို", "အမေရီကာနို"],
  ["ပူတင်း", "ကတ်စတာ"],
  ["ဘရောင်နီ", "ဖတ်ချ်"],
  ["မနက်စာသီးနှံ", "ဂရာနိုလာ"],
  ["ယာဂု", "အုတ်မီးလ်"],
  ["ပီတာမုန့်", "နန်မုန့်"],
  ["ပေါင်မုန့်ကြော်", "ဘေးဂယ်"],
  ["သရက်သီး", "မက်မွန်သီး"],
  ["ချယ်ရီ", "ဘယ်ရီသီး"],
  ["ဖရဲသီး", "သခွားမွှေး"],
  ["ကာရီ", "ဟင်းချို"],
  ["ဖက်ထုပ်", "ပေါင်းမုန့်"],
  ["ခရိုဆောင်", "ပက်စထရီ"],
  ["ပရက်ဇယ်", "ပေါင်မုန့်ချောင်း"],
  ["မရိုနိစ်", "အိုင်ယိုလီ"],
  ["မုန်ညင်းဆော့စ်", "ရယ်လစ်ရှ်"],
  ["ဟော့ဒေါ့", "ဝက်အူချောင်း"],
  ["ဘာဂါ", "ဆန်းဒဝစ်ခ်"],
  ["အုမ်းလက်", "ကြက်ဥမွှေ"],
  ["မီဆို", "ဟင်းရည်"],
  ["တော်တီးယာ", "လိပ်မုန့်"],
  ["ချီလီ", "ကက်စရိုး"],
  ["ချဉ်သီး", "သံလွင်သီး"],
  ["မိုခါ", "ချောကလက်ပူ"],
  ["သကြားရည်", "မိုလေးဆီးစ်"],
  ["ယိုဂတ်", "ပူတင်း"],
  ["ချိစ်ကိတ်", "တာ့တ်"],
  ["အသင့်စားခေါက်ဆွဲ", "အသင့်စားဟင်းချို"],
  ["လာဆာညား", "ကက်စရိုး"],
  ["အသားလုံး", "ဝက်အူချောင်း"],
  ["ရာမင်", "ဥဒွန်"],
  ["ညော့ကီ", "ဖက်ထုပ်"],
  ["ဆေးဖက်ဝင်အရွက်", "အမွှေးအကြိုင်"],
  ["ပူဒီနာ", "ဘာစီလ်"],
  ["မြေပဲထောပတ်", "နူတဲလာ"],
  ["အုန်းနို့", "ဗာဒံနို့"],
  ["ဆိုဘက်", "ရှာဘတ်"],
  ["ဂျယ်လီ", "ယို"],
  ["ဝန်တန်", "ရာဗီအိုလီ"],
  ["ကင်မ်ချီ", "ချဉ်ဟင်းသီးဟင်းရွက်"],
  ["ဖလာဖယ်", "အသားလုံး"],
  ["ပက်စတို", "ဂွါကာမိုလီ"],
  ["ဘာဂက်", "ချီအာဘာတာ"],
  ["နာနတ်သီးပီဇာ", "ဟမ်ပီဇာ"],
  ["အက်ပယ်စိုက်ဒါ", "သစ်သီးရည်"],
  ["လာစီ", "စမူးသီး"],
  ["အုန်းရည်", "အားကစားသောက်ရည်"],
  ["ဆိုဒါ", "ဖိဇ်ရေ"],
  ["တိုနစ်", "ဆယ်လ်ဇာ"],
  ["ဘစ်စကော့တီ", "ကွတ်ကီး"],
  ["မက်ကာရွန်း", "မေရင်း"],
  ["စကုံး", "ဘစ်စကစ်"],
  ["ကာရမယ်", "တော်ဖီ"],
  ["ဟေဇယ်နတ်", "ဗာဒံသီး"],
  ["ကက်ရှူး", "ပစ္စတာချီယို"],
  ["တိုဖူး", "ပါနီးယား"],
  ["အက်ဒါမားမီး", "ပဲစေ့"],
  ["ထောပတ်သီး", "သခွားသီး"],
  ["ပန်းမုံလာ", "ဘရိုကိုလီ"],
  ["ဖရုံသီး", "စကွပ်ရှ်"],
  ["အာလူးကြော်", "ဖရန်ချ်ဖရိုင်း"],
  ["ကေဘက်", "တုတ်ကင်"],
  ["ဖိုး", "ရာမင်"],
  ["စမိုဆာ", "ကွေ့လိပ်"],
  ["ခရိုကက်", "နဂက်"],
  ["အသုပ်", "ကိုယ်လ်စလော"],
  ["ဂရန်နီတာ", "ဆိုဘက်"],
  ["လက်ဖက်အိတ်", "ကော်ဖီစစ်စက္ကူ"],
  ["မာဂရီတာ", "ဒိုင်ကွီရီ"],
  ["ကိုကိုး", "မိုခါ"],
  ["ပါဖေး", "ထရိုင်ဖလ်"],
  ["ပင်လယ်ဆား", "ကျောက်ဆား"],
  ["ကြက်ဥလိပ်", "ဘူရီတို"],
  ["တီရာမီစု", "ချိစ်ကိတ်"],
  ["ပိုင်အခြေ", "မုန့်အခွံ"],
  ["ခြောက်သွေ့စပျစ်", "စွယ်သီးခြောက်"],
  ["ဘယ်ရီယို", "သစ်သီးဂျယ်လီ"],
  ["ချူရို", "ဒိုးနပ်"],
  ["ထမင်းကြော်", "ပါအယ်လာ"],
])

const myanmarHomeDailyPairs = pairs([
  ["ဆိုဖာ", "လက်တင်ခုံ"],
  ["ရေခဲသေတ္တာ", "ရေခဲခန်း"],
  ["သွားတိုက်တံ", "မုတ်ဆိတ်ရိတ်ဓား"],
  ["အဝတ်လျှော်ခြင်း", "ပန်းကန်ဆေးခြင်း"],
  ["တံမြက်စည်း", "မော့ပ်"],
  ["ကုလားကာ", "ဘလိုင်း"],
  ["ဒယ်အိုး", "ဟင်းအိုး"],
  ["အဝတ်ဗီရို", "အဝတ်ခန်း"],
  ["နှိုးစက်နာရီ", "အချိန်တိုင်းစက်"],
  ["ပေါင်မုန့်ဖုတ်စက်", "မိုက်ခရိုဝေ့ဗ်"],
  ["ရေကန်", "ရေချိုးကန်"],
  ["ဖုန်စုပ်စက်", "ရွက်ဖျက်စက်"],
  ["အဝတ်ချိတ်", "ချိတ်"],
  ["ကြမ်းခင်းဖျာ", "ကော်ဇော"],
  ["အိပ်ယာဘေးစားပွဲ", "စာရေးစားပွဲ"],
  ["ရေချိုးခန်း", "ရေပန်းခေါင်း"],
  ["ဆပ်ပြာဘူး", "လိုးရှင်းဘူး"],
  ["ခုံရှည်", "ထိုင်ခုံတန်း"],
  ["ရေနွေးအိုး", "လက်ဖက်ရည်အိုး"],
  ["စာတိုက်ပုံး", "ပစ္စည်းပုံး"],
  ["ပန်းကန်တင်စင်", "အခြောက်ခံစင်"],
  ["အဝတ်လျှော်ခြင်းခြင်း", "သိုလှောင်ပုံး"],
  ["ခေါင်းအုံးစွပ်", "အိပ်ယာခင်း"],
  ["မွေ့ရာ", "ဖူတွန်"],
  ["စောင်", "အိပ်ယာထူစောင်"],
  ["ကုလားကာတန်း", "စင်ထောက်တံ"],
  ["ရီမုတ်", "မီးခလုတ်"],
  ["မျက်နှာကျက်ပန်ကာ", "စားပွဲပန်ကာ"],
  ["တံခါးရှေ့ဖျာ", "ရေချိုးခန်းဖျာ"],
  ["တံခါးလက်ကိုင်", "ဗီဒိုလက်ကိုင်"],
  ["မီးဖို", "အိုဗင်"],
  ["ကြော်ဒယ်အိုး", "ဟင်းရည်အိုး"],
  ["ဓား", "ကတ်ကြေး"],
  ["ပန်းကန်စင်", "ခွက်စင်"],
  ["စားပွဲခုံ", "ကော်ဖီစားပွဲ"],
  ["အဝတ်လျှော်ဆပ်ပြာ", "အဝတ်နူးဆေး"],
  ["မီးပူ", "ငွေ့ပူစက်"],
  ["တောင်း", "ရေပုံး"],
  ["ဖုန်တင်ခွက်", "သန့်ရှင်းရေးတံ"],
  ["ခေါင်းလျှော်ရည်ဘူး", "ပျော့ဆေးဘူး"],
  ["အိမ်သာစက္ကူ", "စက္ကူသုတ်ပဝါ"],
  ["ရေချိုးပဝါ", "လက်သုတ်ပဝါ"],
  ["မတ်", "ဖန်ခွက်"],
  ["ဖျော်စက်", "မွှေစက်"],
  ["ထမင်းပေါင်းအိုး", "အချိန်နှေးချက်အိုး"],
  ["ပန်းကန်ဆေးဖော့", "ပန်းကန်ဆေးတံ"],
  ["အဝတ်လျှော်ခန်း", "သိုလှောင်ခန်း"],
  ["အမှိုက်ပုံး", "ပြန်လည်အသုံးပြုအမှိုက်ပုံး"],
  ["အိပ်ရာဘောင်", "ခေါင်းမှီဘောင်"],
  ["မှန်ဗီဒို", "ဆေးဗီဒို"],
  ["ဖိနပ်စင်", "အင်္ကျီချိတ်စင်"],
  ["ဖုန်စုပ်အိတ်", "အမှိုက်အိတ်"],
  ["ကူရှင်", "ခေါင်းအုံး"],
  ["စင်", "ဗီဒို"],
  ["စားပွဲမီးအိမ်", "ကြမ်းပြင်မီးအိမ်"],
  ["မီးခလုတ်", "တံခါးခေါ်ခလုတ်"],
  ["ရေခဲခန်းထည့်ဗန်း", "ရေခဲပုံး"],
  ["ဆပ်ပြာတုံး", "ရေချိုးဂျယ်"],
  ["အဝတ်လျှော်စက်", "အခြောက်ခံစက်"],
  ["အဝတ်လျှော်ကြိုး", "အဝတ်တင်စင်"],
  ["ရေချိုးခန်းရေကန်", "မီးဖိုချောင်ရေကန်"],
  ["ရေအိုး", "ရေသွန်းခွက်"],
  ["ပန်းကန်ဆေးစက်", "အခြောက်ခံစင်"],
  ["အင်္ကျီဖုံး", "အိုဗင်လက်အိတ်"],
  ["ရေဒီယိုနာရီ", "နှိုးစက်နာရီ"],
  ["မီးဖိုချောင်ပဝါ", "စားပွဲတင်ပဝါ"],
  ["သိုလှောင်ပုံး", "ဒရော်အံဆွဲစီစဉ်ပုံး"],
  ["ဖုန်စုပ်ပိုက်", "ဥယျာဉ်ပိုက်"],
  ["နံရံစင်", "စာအုပ်စင်"],
  ["အိပ်ခန်း", "ဧည့်ခန်း"],
  ["စားပွဲထိုင်ခုံ", "ဘားထိုင်ခုံ"],
  ["ဆပ်ပြာထည့်ခွက်", "သွားတိုက်တံထည့်ခွက်"],
  ["တစ်ရှူးပုံး", "စိုစွတ်သုတ်ပုံး"],
  ["ပြတင်းပေါက်ဘောင်", "တံခါးဘောင်"],
  ["ဒယ်အိုးအဖုံး", "ဟင်းအိုးအဖုံး"],
  ["ရေစစ်စက်", "ရေနွေးအိုး"],
  ["အိပ်ရာဘေးမီးအိမ်", "လျှောက်လမ်းမီးအိမ်"],
  ["အိမ်ဝတ်အင်္ကျီ", "အိပ်ဝတ်"],
  ["အဝတ်လျှော်ဆပ်ပြာ", "ပန်းကန်ဆေးဆပ်ပြာ"],
  ["သန့်ရှင်းရေးဖျန်းဆေး", "လေသန့်ဆေး"],
  ["ခန်းပုံး", "သိုလှောင်ခန်း"],
  ["အိမ်သာသန့်စင်တံ", "ပုလင်းသန့်စင်တံ"],
  ["မွှေခွက်", "အသုပ်ခွက်"],
  ["အမွှေးအကြိုင်စင်", "ဓားတိုင်"],
  ["အိပ်ယာခင်းဗီရို", "စားစရာဗီရို"],
  ["အိမ်သော့", "စာတိုက်ပုံးသော့"],
  ["တိရစ္ဆာန်အိပ်ရာ", "ကလေးအိပ်ရာ"],
  ["အဝတ်လျှော်ခြင်းခြင်း", "ကစားစရာတောင်း"],
  ["စောင်တင်တန်း", "ပဝါတန်း"],
  ["ရေဖျန်းဘူး", "ဖျန်းပုလင်း"],
  ["ရေမြောင်းပေါက်", "ပိတ်ခွက်"],
  ["မုန့်လိပ်တံ", "မွှေတံ"],
  ["တိုင်းခွက်", "တိုင်းဇွန်း"],
  ["နာရီဘက်ထရီ", "ရီမုတ်ဘက်ထရီ"],
  ["ရေချိုးခန်းကုလားကာ", "မှန်တံခါး"],
  ["စက္ကူမီးအိမ်", "မျက်နှာကျက်မီးအိမ်"],
  ["အဝတ်ကလစ်", "အဝတ်ချိတ်"],
  ["မီးဖိုချောင်အချိန်တိုင်းစက်", "ကြက်ဥအချိန်တိုင်းစက်"],
  ["အိမ်ရှေ့ဝင်ပေါက်", "အပြင်ဘက်ထိုင်နေရာ"],
  ["ဝင်ပေါက်ခန်း", "လျှောက်လမ်း"],
])

const myanmarTravelNaturePairs = pairs([
  ["ကျွန်း", "ကျွန်းဆွယ်"],
  ["ရေတံခွန်", "ရေပန်း"],
  ["တဲ", "သစ်သားအိမ်ငယ်"],
  ["နိုင်ငံကူးလက်မှတ်", "ဗီဇာ"],
  ["ခရီးဆောင်သေတ္တာ", "ခရီးဆောင်အိတ်"],
  ["မီးပုံ", "မီးဖို"],
  ["ရေခဲမြစ်", "ရေခဲကျွန်း"],
  ["မီးတောင်", "ရေပူပန်း"],
  ["တောလမ်း", "လမ်းကြောင်း"],
  ["ဆာဖာရီ", "တိရစ္ဆာန်ဥယျာဉ်"],
  ["မြေပုံ", "ကွန်ပတ်"],
  ["ကယက်", "ကနူး"],
  ["လေယာဉ်ဝန်ထမ်း", "လေယာဉ်မှူး"],
  ["အငှားအိမ်", "ဟိုတယ်"],
  ["ဆိပ်ကမ်း", "လှေဆိပ်"],
  ["ပင်လယ်ကျောက်တန်း", "ပင်လယ်ရေမှော်"],
  ["သက်တံ", "နေဝင်ချိန်"],
  ["ထင်းရှူးပင်", "အုန်းပင်"],
  ["မိုတယ်", "ဟော်စတယ်"],
  ["တောင်တက်ဖိနပ်", "နှင်းဖိနပ်"],
  ["လဂွန်း", "ပင်လယ်ကွေ့"],
  ["ကျောက်ချိုင့်", "ချိုင့်ဝှမ်း"],
  ["တောင်ကျော", "ကမ်းပါး"],
  ["သဲကုန်း", "ကုန်း"],
  ["ကျောက်စရစ်", "ခွံ"],
  ["ဆိပ်ကမ်းလည်ပတ်ခရီး", "ဖယ်ရီ"],
  ["စီးနင်းခွင့်ကတ်", "လက်မှတ်"],
  ["စခန်းချရာနေရာ", "ပျော်ပွဲစားနေရာ"],
  ["တောင်ထိပ်", "တောင်အမြင့်ဆုံးနေရာ"],
  ["မိုးခိုး", "နှင်းမှုန်"],
  ["မိုးသစ်တော", "စိုစွတ်မြေ"],
  ["ဂူ", "ကျောက်ဂူ"],
  ["မြက်ခင်း", "လယ်ကွင်း"],
  ["သစ်တောလမ်း", "တောလမ်း"],
  ["မြစ်ကမ်း", "ကမ်းရိုးတန်း"],
  ["ဝေလငါး", "ဒေါ်ဖင်"],
  ["ပင်လယ်ဖျံ", "ရေဖျံ"],
  ["ရေအိုင်", "ချောင်းငယ်"],
  ["ဘယ်ရီပင်", "နွယ်ပင်"],
  ["အုန်းပင်အုပ်", "သစ်တော"],
  ["ရေဗူး", "ကန်တင်း"],
  ["ကျောပိုးခရီးသွား", "စခန်းချသူ"],
  ["နေထွက်ချိန်", "အာရုဏ်တက်"],
  ["ညနေမှောင်ရီ", "နေလုံးဝင်ချိန်"],
  ["သဲကန္တာရစခန်း", "တောင်တန်းအိမ်လေး"],
  ["ရေတက်", "လှိုင်း"],
  ["ကျောက်ချ", "လှေတင်မောင်းတံ"],
  ["လမ်းစ", "စစ်ဆေးရေးမှတ်တိုင်"],
  ["နှင်းကျခြင်း", "နှင်းပြိုကျခြင်း"],
  ["တောပန်း", "ဖန်းပင်"],
  ["သစ်သားလမ်းခင်း", "ဆိပ်ခံတံတား"],
  ["လည်ပင်းခေါင်းအုံး", "ခရီးသွားခေါင်းအုံး"],
  ["မျက်မှန်ကြီး", "အဝေးကြည့်မှန်ပြောင်း"],
  ["အကြားစာ", "ဂရန်နိုလာဘား"],
  ["ဂိတ်", "တာမီနယ်"],
  ["စီးနင်းရန်တန်း", "လုံခြုံရေးတန်း"],
  ["ခရီးသွားလမ်းညွှန်", "မြေပုံစာအုပ်"],
  ["ကမ်းခြေပဝါ", "ပျော်ပွဲစားစောင်"],
  ["အသက်ကယ်လှေ", "ရေဖောင်"],
  ["လှော်တံ", "တက်လှော်တံ"],
  ["ဂျက်လက်", "လှုပ်ရှားမှုမအီမသာဖြစ်ခြင်း"],
  ["တောင်ပေါ်အိမ်", "ကမ်းခြေအိမ်ငယ်"],
  ["ဂျာကင်", "မိုးကာ"],
  ["မိုးကုပ်စက်ဝိုင်း", "မြို့ကန့်သတ်လိုင်း"],
  ["စခန်းချရာ", "အခြေစိုက်စခန်း"],
  ["မီးပုံး", "စခန်းမီးအိမ်"],
  ["ခြင်", "ပျား"],
  ["တောလမ်းဆိုင်းဘုတ်", "လမ်းဆိုင်းဘုတ်"],
  ["နယ်စပ်", "အကောက်ခွန်"],
  ["နှင်းလျှောစက်", "ကေဘယ်ကား"],
  ["အေးမြေပြင်", "မြက်ပြင်ကြီး"],
  ["ရေဗူး", "သာမိုစ်"],
  ["တဲချိတ်သံ", "ကြိုးတိုင်"],
  ["ပို့စ်ကတ်", "အမှတ်တရပစ္စည်း"],
  ["ပြတိုက်", "အထိမ်းအမှတ်ကျောက်တိုင်"],
  ["အပျက်အစီး", "ဘုရားကျောင်းဟောင်း"],
  ["အမျိုးသားဥယျာဉ်", "အပင်ဥယျာဉ်"],
  ["ကြိုးတံတား", "လွင့်တင်တံတား"],
  ["ငှက်အသိုက်", "တောတွင်းအိမ်ပေါက်"],
  ["အုန်းပင်", "ငှက်ပျောပင်"],
  ["ဟာမော့ခ်", "ကမ်းခြေထိုင်ခုံ"],
  ["မိုးကာအင်္ကျီ", "ပေါင်ချို"],
  ["စခန်းမီးဖို", "အကင်စက်"],
  ["ပျော်ပွဲစားတောင်း", "အအေးပုံး"],
  ["မီးပြတိုက်", "အချက်ပြမီး"],
  ["လိပ်", "ကုန်းလိပ်"],
  ["ပင်ဂွင်း", "ပင်လယ်ငှက်"],
  ["သစ်သားအိမ်ပြတင်းပေါက်", "လှေပြတင်းပေါက်"],
  ["ကြယ်ကြည့်ခြင်း", "ငှက်ကြည့်ခြင်း"],
  ["သစ်ခွ", "နှင်းဆီဖြူ"],
  ["မော့စ်", "လိုင်ခင်"],
  ["မြေသားလမ်း", "ကျောက်စရစ်လမ်း"],
  ["လမ်းမှတ်သား", "မိုင်တိုင်"],
  ["ပင်လယ်လေညင်း", "တောင်လေ"],
  ["ခရီးသွားဘတ်စ်ကား", "ရှပ်တယ်ကား"],
  ["လှိုင်းကန်", "လဂွန်း"],
  ["စခန်းထိုင်ခုံ", "ကမ်းခြေထိုင်ခုံလေး"],
  ["ခရီးဆောင်အိတ်ငယ်", "နိုင်ငံကူးလက်မှတ်အိတ်"],
  ["တောအိမ်", "ရေအိုင်အိမ်"],
])

const myanmarSportsHobbiesPairs = pairs([
  ["ဘောလုံး", "ရပ်ဂ်ဘီ"],
  ["တင်းနစ်", "ကြက်တောင်"],
  ["ရေကူး", "ရေငုပ်"],
  ["စစ်တုရင်", "ချက်ကာ"],
  ["ပန်းချီ", "ရေးဆွဲခြင်း"],
  ["ဂီတာ", "ယူကူလီလီ"],
  ["ဒရမ်", "တံပိုးလေး"],
  ["ဘတ်စကက်ဘော", "ဗော်လီဘော"],
  ["စကိတ်ဘုတ်", "ဆာဖ်ဘုတ်"],
  ["ငါးမျှားခြင်း", "အမဲလိုက်ခြင်း"],
  ["ဘိုးလင်း", "ဒတ်စ်"],
  ["ယောဂ", "ပီလိတ်တီးစ်"],
  ["စက္ကူခေါက်", "ချည်ထိုး"],
  ["ကာရာအိုကေ", "ဖျော်ဖြေပွဲ"],
  ["ပဟေဠိ", "စကားဝှက်"],
  ["နှင်းဘုတ်", "စကီး"],
  ["ဘေ့စ်ဘော", "ကရစ်ကက်"],
  ["လက်ဝှေ့", "နပန်း"],
  ["ဘဲလေး", "ဂျင်နာစတစ်"],
  ["ကွန်မစ်စာအုပ်", "မန်ဂါ"],
  ["စောကာ", "ဖူဆယ်"],
  ["မရာသွန်", "အမြန်ပြေး"],
  ["စက်ဘီးစီးခြင်း", "ပြေးခြင်း"],
  ["ဂေါ့ဖ်", "မီနီဂေါ့ဖ်"],
  ["ဘောလုံးထိန်း", "ပေးပို့ခြင်း"],
  ["တောင်တက်", "တောင်လျှောက်"],
  ["ရေမျက်နှာပြင်ကြည့်ရေငုပ်", "စကူဘာရေငုပ်"],
  ["အိုးလုပ်ခြင်း", "ကြွေထည်လုပ်ခြင်း"],
  ["လက်ရေးလှ", "စာလုံးအလှရေး"],
  ["ချည်ထိုး", "ချုပ်လုပ်ခြင်း"],
  ["စန္ဒယား", "ကီးဘုတ်"],
  ["ဖလူး", "ရီကော်ဒါ"],
  ["ဗိုင်အိုလင်", "ဆဲလို"],
  ["သရုပ်ဆောင်ခြင်း", "ချက်ချင်းသရုပ်ဆောင်ခြင်း"],
  ["ဘောလုံးလှည့်ကစား", "မှော်ပညာ"],
  ["ကတ်အလှည့်", "ပဟေဠိလှည့်ကွက်"],
  ["စခန်းချ", "နောက်ကျောပိုးခရီး"],
  ["ငှက်ကြည့်", "ကြယ်ကြည့်"],
  ["မြှားပစ်", "ဒတ်စ်"],
  ["ကာရာတေး", "တက်ကွန်းဒို"],
  ["ဓားကစား", "ကန်ဒို"],
  ["ဘုတ်ဂိမ်း", "ကတ်ဂိမ်း"],
  ["ဆူဒိုကူ", "စကားဝှက်စာမေးပွဲ"],
  ["ရွှံ့", "စလိမ်း"],
  ["ဓာတ်ပုံရိုက်", "ဗီဒီယိုရိုက်"],
  ["တံဆိပ်ခေါင်းစု", "ဒင်္ဂါးစု"],
  ["မော်ဒယ်ရထား", "အဝေးထိန်းကား"],
  ["အဝေးထိန်းလေယာဉ်", "ဒရုန်း"],
  ["ဆာဖ်စီးခြင်း", "ဝိတ်ဘုတ်စီးခြင်း"],
  ["စကိတ်စီးခြင်း", "ရေခဲစကိတ်စီးခြင်း"],
  ["အဝေးခုန်", "အမြင့်ခုန်"],
  ["သံလုံးပစ်", "ဒစ်စကပ်ပစ်"],
  ["စားပွဲတင်တင်းနစ်", "လေဟော်ကီ"],
  ["ဘီလီယတ်", "စနူကာ"],
  ["သံစုံတေးအဖွဲ့", "တီးဝိုင်း"],
  ["သီချင်းရေးခြင်း", "ကဗျာရေးခြင်း"],
  ["စာဖတ်အသင်း", "ဆွေးနွေးအသင်း"],
  ["ကော့စပလေး", "အဝတ်အစားဒီဇိုင်း"],
  ["မုန့်ဖုတ်", "ဟင်းချက်"],
  ["ငါးမျှားချောင်း", "ပိုက်ကွန်"],
  ["စခန်းမီးဖို", "သယ်ဆောင်အကင်စက်"],
  ["စွန်လွှတ်", "စက္ကူလေယာဉ်"],
  ["ပဟေဠိတုံး", "ဂျစ်ဆော"],
  ["တောင်ထိပ်ခုန်", "ကြိုးခုန်ချ"],
  ["ကိုယ်ကာယတည်ဆောက်", "အားမြှင့်လေ့ကျင့်"],
  ["ဘင်ချ်ပရက်စ်", "ဒက်လစ်ဖ်"],
  ["ရေခဲဟော်ကီ", "မြေပြင်ဟော်ကီ"],
  ["လက်ဘော", "နက်ဘော"],
  ["လှေတန်းလှော်", "ကနူးလှော်"],
  ["ရွက်လှေစီး", "လေတိုက်လှေစီး"],
  ["မြင်းစီး", "ကုလားအုတ်စီး"],
  ["ခွေးအတားအဆီးပြိုင်ပွဲ", "မြင်းခုန်ပြိုင်ပွဲ"],
  ["မှော်ကတ်", "ကစားကတ်"],
  ["လီဂိုတည်ဆောက်", "မော်ဒယ်ကစ်"],
  ["ချည်ပန်းထိုး", "အမှတ်ဖြတ်ချုပ်"],
  ["သစ်သားထု", "သစ်သားပန်းပု"],
  ["ဟစ်ဟော့", "ဘရိတ်ဒန့်စ်"],
  ["ဆာလ်ဆာ", "တန်ဂို"],
  ["တရားထိုင်", "အသက်ရှုလေ့ကျင့်ခန်း"],
  ["လေ့လာခရီး", "စခန်းချခရီး"],
  ["ရုပ်ရှင်အသင်း", "ပြဇာတ်အသင်း"],
  ["ဗဟုသုတည", "မေးခွန်းပြိုင်ပွဲ"],
  ["ထွက်လမ်းရှာခန်း", "ရတနာလိုက်ရှာခြင်း"],
  ["ရတနာမြေပုံ", "သဲလွန်စစာရွက်"],
  ["နှင်းလျှော", "ရေပုံးလျှော"],
  ["ပါကူ", "ဂျင်နာစတစ်"],
  ["ပန်းချီပုတီးရောင်ခြယ်", "စကက်ချ်ရေး"],
  ["ရေကန်မွေးမြူခြင်း", "ဥယျာဉ်စိုက်ခြင်း"],
  ["ပန်းစည်းအလှဆင်", "စားပွဲပြင်ဆင်"],
  ["နှင်းလူလုပ်ခြင်း", "သဲအရုပ်လုပ်ခြင်း"],
  ["ပင်ပေါင်လက်တံ", "တင်းနစ်ရက်ကက်"],
  ["ဂိုးသမား", "နောက်ခံကစားသမား"],
  ["ဒိုင်လူကြီး", "နည်းပြ"],
  ["ရမှတ်ဘုတ်", "အချိန်တိုင်းစက်"],
  ["အသင်းခေါင်းဆောင်", "ကလပ်ဥက္ကဋ္ဌ"],
  ["အားပေးအဖွဲ့", "ကပွဲအသင်း"],
  ["အဝတ်အစား", "ယူနီဖောင်း"],
  ["ခရိုကေး", "ဘော့ချေ"],
  ["ဖိုမ်လှိမ့်တံ", "ယောဂဖျာ"],
  ["စကက်ချ်စာအုပ်", "ကန်ဗတ်စာရွက်"],
])

const myanmarSchoolWorkPairs = pairs([
  ["ဆရာ", "ပါမောက္ခ"],
  ["အိမ်စာ", "စာမေးပွဲတို"],
  ["မှတ်စုစာအုပ်", "သင်ခန်းစာစာအုပ်"],
  ["စက္ကူချုပ်စက်", "စက္ကူကလစ်"],
  ["အဖြူဘုတ်", "အမဲဘုတ်"],
  ["အလုပ်သင်", "အကူ"],
  ["အစည်းအဝေး", "လေ့ကျင့်ခန်းဆွေးနွေးပွဲ"],
  ["ကိုယ်ရေးရာဇဝင်", "အလုပ်နမူနာစု"],
  ["နောက်ဆုံးရက်", "အချိန်ဇယား"],
  ["တင်ဆက်မှု", "ဟောပြောပို့ချမှု"],
  ["မန်နေဂျာ", "ကြီးကြပ်သူ"],
  ["ယူနီဖောင်း", "အဝတ်အစားစည်းကမ်း"],
  ["တွက်စက်", "တွက်ခွက်"],
  ["လော့ကာ", "ဒရော်အံဆွဲ"],
  ["ကျောင်းခေါင်းလောင်း", "လက်သံချောင်း"],
  ["မာကာ", "ကရိုင်ယွန်"],
  ["ကလစ်ဘုတ်", "ဖိုင်တွဲ"],
  ["စာမေးပွဲ", "အင်တာဗျူး"],
  ["ဓာတ်ခွဲခန်း", "အလုပ်ရုံ"],
  ["လက်မှတ်", "ဒီပလိုမာ"],
  ["ကျောင်းအုပ်", "ဒီန်"],
  ["စာသင်ခန်း", "ဟောပြောခန်း"],
  ["စားပွဲခုံ", "ရုံးအကာခန်း"],
  ["ထွက်ခွင့်ကတ်", "ဧည့်သည်ကတ်"],
  ["ဆောင်းပါး", "အစီရင်ခံစာ"],
  ["သင်ရိုးညွှန်းတမ်း", "အစီအစဉ်စာရင်း"],
  ["သင်ခန်းစာ", "သင်ကြားညွှန်ကြားမှု"],
  ["လမ်းညွှန်ဆရာ", "အိမ်စာကူဆရာ"],
  ["အလုပ်သင်ကာလ", "လက်တွေ့သင်တန်း"],
  ["လစာစာရင်း", "ငွေတောင်းခံလွှာ"],
  ["မှတ်စု", "အသိပေးစာ"],
  ["မိတ်ဆက်သင်တန်း", "အလုပ်ဝင်မိတ်ဆက်"],
  ["အမည်တံဆိပ်", "ကတ်ပြား"],
  ["တက်ရောက်မှု", "အလုပ်ချိန်မှတ်တမ်း"],
  ["လုပ်ငန်းအလှည့်", "အချိန်ဇယား"],
  ["ဧည့်ကြို", "ရှေ့ကောင်တာ"],
  ["ဝန်ထမ်းခန်း", "နားခန်း"],
  ["လော့ကာခန်း", "သိုလှောင်ခန်း"],
  ["ပရောဂျက်", "တာဝန်စာ"],
  ["စီစဉ်စာအုပ်", "ပြက္ခဒိန်"],
  ["စာရွက်မှတ်စု", "ကပ်မှတ်စာ"],
  ["မိတ္တူကူးစက်", "ပရင်တာ"],
  ["ပရိုဂျက်တာဖန်သား", "အဖြူဘုတ်"],
  ["ဉာဏ်ကြီးပွားဆွေးနွေး", "ဆွေးနွေးပွဲ"],
  ["မန်နေဂျာအစည်းအဝေး", "အသင်းတိုညှိနှိုင်းမှု"],
  ["လစာစာရင်း", "ဘတ်ဂျက်"],
  ["အမှတ်", "ရမှတ်"],
  ["ယူနီဖောင်းအင်္ကျီ", "အမည်တံဆိပ်"],
  ["စာရင်းဇယား", "အစီရင်ခံစာ"],
  ["စားပွဲမီးအိမ်", "မော်နီတာမီး"],
  ["တွက်စက်အက်ပ်", "ဇယားအက်ပ်"],
  ["လက်မှတ်ရေး", "အတိုကောက်ရေး"],
  ["သုတေသန", "စစ်တမ်း"],
  ["စမ်းသပ်မှု", "လေ့လာမှု"],
  ["တာဝန်စာရွက်", "အမှတ်ပေးစံ"],
  ["အဖွဲ့ပရောဂျက်", "အမှုကိစ္စလေ့လာမှု"],
  ["တက်ရောက်မှုစာရွက်", "အမည်စာရင်း"],
  ["အလုပ်အကိုင်ပြပွဲ", "ဖွင့်လှစ်ပြပွဲ"],
  ["လေ့ကျင့်သင်တန်း", "ဆီမီနာ"],
  ["မိတ်ဆက်အပတ်", "စာမေးပွဲအပတ်"],
  ["ရုံးထိုင်ခုံ", "စားပွဲထိုင်ခုံ"],
  ["အကာခန်းနံရံ", "ဘုတ်နံရံ"],
  ["သင်ခန်းစာအခန်း", "လေ့ကျင့်စာမျက်နှာ"],
  ["စီစဉ်အက်ပ်", "ပြက္ခဒိန်အက်ပ်"],
  ["မှတ်စုစာအုပ်ငယ်", "မှတ်စုစာအုပ်"],
  ["ရလဒ်စာရင်း", "မှတ်တမ်းစာရွက်"],
  ["ထောက်ခံစာ", "လက်မှတ်"],
  ["ဖုန်းအင်တာဗျူး", "ဗီဒီယိုအင်တာဗျူး"],
  ["ဘာသာရပ်", "အတန်း"],
  ["အထူးဘာသာ", "နောက်ထပ်ဘာသာ"],
  ["လေ့လာခရီး", "ဓာတ်ခွဲခန်းသွားကြည့်ခြင်း"],
  ["သင်ကြားရေးအဖွဲ့", "ဌာန"],
  ["စာအုပ်ခွဲမှတ်တံဆိပ်", "ဘိုင်ဒါခွဲမှတ်တံဆိပ်"],
  ["စက္ကူထည့်ခွက်", "စာပုံး"],
  ["သန့်ရှင်းရေးခန်း", "ပစ္စည်းခန်း"],
  ["စားသောက်ခန်း", "အစားအသောက်ခန်းမ"],
  ["ခန်းမ", "အားကစားခန်းမ"],
  ["စာသင်ကာလ", "သုံးလပတ်"],
  ["လစာဖြတ်ပိုင်း", "ပြေစာ"],
  ["ကုမ္ပဏီမူဝါဒ", "စည်းကမ်းစာအုပ်"],
  ["အသင်းခေါင်းဆောင်", "ကြီးကြပ်သူ"],
  ["ကျောင်းကား", "ရှပ်တယ်ကား"],
  ["အတန်းဓာတ်ပုံ", "ကတ်ပုံ"],
  ["ပိုစတာဘုတ်", "သုံးဖက်ခေါက်ဘုတ်"],
  ["သိပ္ပံပြပွဲ", "စာအုပ်ပြပွဲ"],
  ["လက်မှုပညာစက္ကူ", "ပရင်တာစာရွက်"],
  ["အချိန်တိုင်းစက်", "စတော်ဝက်ချ်"],
  ["ဧည့်ကြိုဖုန်း", "အကူအညီတောင်းလွှာ"],
  ["စစ်ဆေးစာရင်း", "လေ့ကျင့်စာရွက်"],
  ["မေးဖြေ", "ဆွေးနွေးမှု"],
  ["ပြင်ဆင်မှု", "မူကြမ်း"],
  ["နည်းပြ", "အကြံပေး"],
  ["အလှည့်မန်နေဂျာ", "ကြမ်းပြင်မန်နေဂျာ"],
  ["ရုံးနေ့လယ်စာ", "ကျောင်းနေ့လယ်စာ"],
  ["မှတ်တမ်းစာရွက်", "ကိုယ်ရေးရာဇဝင်"],
  ["စီစဉ်ကပ်စတစ်ကာ", "ကပ်မှတ်စာ"],
  ["အိမ်စာဖိုင်တွဲ", "နေ့လယ်စာပုံး"],
  ["ကုမ္ပဏီအီးမေးလ်", "မှတ်စုစာ"],
  ["စားပွဲစီစဉ်ပုံး", "ပစ္စည်းထည့်စင်"],
  ["အလုပ်ရုံခန်း", "အစည်းအဝေးခန်း"],
])

const myanmarTechMediaPairs = pairs([
  ["ကီးဘုတ်", "စန္ဒယား"],
  ["နားကြပ်", "နားထဲထည့်နားကြပ်"],
  ["အားသွင်းကြိုး", "အဒပ်တာ"],
  ["တိုက်ရိုက်ထုတ်လွှင့်မှု", "အသံလွှင့်မှု"],
  ["ပေါ့ဒ်ကတ်စ်", "ရေဒီယို"],
  ["ကင်မရာ", "ဗီဒီယိုကင်မရာ"],
  ["မိုက်ကရိုဖုန်း", "စပီကာ"],
  ["မောက်စ်", "ထိတွေ့ပြား"],
  ["စကားဝှက်", "PIN နံပါတ်"],
  ["ဘရောက်ဇာ", "ရှာဖွေရေးစက်"],
  ["အက်ပ်", "ဝက်ဘ်ဆိုက်"],
  ["အသိပေးချက်", "နှိုးစက်"],
  ["ဒရုန်း", "ရဟတ်ယာဉ်"],
  ["ပရိုဂျက်တာ", "မော်နီတာ"],
  ["ဘက်ထရီ", "မီးစက်"],
  ["ကလောက်", "ဆာဗာ"],
  ["မျက်နှာပြင်ဖမ်းပုံ", "ဓာတ်ပုံ"],
  ["ဂျွိုက်စတစ်", "ဂိမ်းထိန်းခလုတ်"],
  ["ပရင်တာ", "စကင်နာ"],
  ["သီချင်းစာရင်း", "အယ်လ်ဘမ်"],
  ["တက်ဘလက်", "e-book စက်"],
  ["ရောက်တာ", "မိုဒမ်"],
  ["ဟတ်ဒ်ဒရိုက်", "USB ဒရိုက်"],
  ["တင်ပို့", "ဒေါင်းလုဒ်"],
  ["အီမိုဂျီ", "စတစ်ကာ"],
  ["ကိုယ်စားပုံ", "ပရိုဖိုင်ပုံ"],
  ["ကီးဘုတ်ဖြတ်လမ်း", "မက်ခရို"],
  ["စစ်ထုတ်အကျိုးသက်ရောက်မှု", "လင့်စ်"],
  ["သုံးချောင်းထောက်", "တိုင်"],
  ["တိုက်ရိုက်ဗီဒီယို", "ဗီဒီယိုခေါ်ဆိုမှု"],
  ["စာတို", "အီးမေးလ်"],
  ["နာရီ", "စမတ်နာရီ"],
  ["ဂိမ်းစက်", "PC"],
  ["လက်တော့ပ်တင်စင်", "မော်နီတာတိုင်"],
  ["ဖိုင်ယာဝေါ", "ဗိုင်းရပ်စ်ကာကွယ်စနစ်"],
  ["ဘရောက်ဇာတပ်", "ဝင်းဒိုး"],
  ["စာမှတ်", "အနှစ်သက်ဆုံး"],
  ["ရှာဖွေရေးဘား", "လိပ်စာဘား"],
  ["ပေါ့ဒ်ကတ်စ်အပိုင်း", "ရေဒီယိုအစီအစဉ်ပိုင်း"],
  ["သီချင်းစာရင်းအဖုံး", "အယ်လ်ဘမ်အနုပညာ"],
  ["VR မျက်မှန်", "ဟယ်လ်မက်"],
  ["စမတ်စပီကာ", "အသံအကူ"],
  ["ရီမုတ်", "ဂိမ်းပက်"],
  ["ကီးဘုတ်မီး", "မျက်နှာပြင်အလင်း"],
  ["ဒေတာကြိုး", "မီးကြိုး"],
  ["ပရောက်စီ", "VPN"],
  ["အသုံးပြုသူအမည်", "လက်ကိုင်အမည်"],
  ["ကလောက်ဘက်အပ်", "မှတ်တမ်းသိမ်းဆည်းမှု"],
  ["ဖိုလ်ဒါ", "ဒိုင်ရက်ထရီ"],
  ["ကာဆာ", "ညွှန်ပြခလုတ်"],
  ["ကုဒ်တည်းဖြတ်စက်", "တာမီနယ်"],
  ["ဘဂ်", "ချို့ယွင်းချက်"],
  ["ပြင်ဆင်ချက်", "အပ်ဒိတ်"],
  ["စမ်းသပ်ဗားရှင်း", "ဒေမို"],
  ["ပုံသေး", "ပိုစတာ"],
  ["တိုက်ရိုက်ချတ်", "မှတ်ချက်ကဏ္ဍ"],
  ["အသိပေးတံဆိပ်", "သတိပေးအိုင်ကွန်"],
  ["ချက်ဘော့", "အုပ်ချုပ်သူ"],
  ["ကြိုးမဲ့မောက်စ်", "ဘလူးတုသ်စပီကာ"],
  ["ထိတွေ့မျက်နှာပြင်", "ထိတွေ့ပြား"],
  ["ကင်မရာရိုလ်", "ပုံပြခန်း"],
  ["ခေါင်းတပ်မိုက်", "ဘွန်းမိုက်"],
  ["ထုတ်လွှင့်အက်ပ်", "ဗီဒီယိုအက်ပ်"],
  ["အသံမှတ်စု", "အသံနုတ်စာ"],
  ["ရင်မီး", "စားပွဲမီးအိမ်"],
  ["အားသွင်းတုံး", "ပါဝါဘဏ်"],
  ["မှန်မဲ့ကင်မရာ", "DSLR"],
  ["မိုက်ခရိုချစ်ပ်", "ဆားကစ်ဘုတ်"],
  ["လည်ပတ်မှုစနစ်", "ဆော့ဖ်ဝဲ"],
  ["ဆော့ဖ်ဝဲ", "ဖမ်ဝဲ"],
  ["လင့်ခ်", "QR ကုဒ်"],
  ["မျက်နှာပြင်မျှဝေမှု", "ပရိုဂျက်တာမုဒ်"],
  ["အသိပေးသံ", "ဖုန်းမြည်သံ"],
  ["ပေါ့ဒ်ကတ်စ်တင်ဆက်သူ", "ရေဒီယိုတင်ဆက်သူ"],
  ["ကလောက်သိုလှောင်မှု", "ပြင်ပဒရိုက်"],
  ["တည်းဖြတ်", "ဖြတ်တောက်"],
  ["ဓာတ်ပုံဖီလ်တာ", "ဗီဒီယိုအကျိုးသက်ရောက်မှု"],
  ["USB ပေါက်", "HDMI ပေါက်"],
  ["ကုဒ်ရေးခြင်း", "စကရစ်ရေးခြင်း"],
  ["ဆာဗာရက်", "ဒက်စတော့ပ်ကွန်ပျူတာ"],
  ["မော်နီတာတင်စင်", "ဒေါက်ကင်းစခန်း"],
  ["ထိန်းချုပ်ခန်း", "စတူဒီယို"],
  ["စာတန်း", "စာတန်းထိုး"],
  ["လက်ဗွေဖတ်စနစ်", "မျက်နှာဖတ်စနစ်"],
  ["အမှောင်မုဒ်", "ညအလင်း"],
  ["ဝက်ဘ်ကင်မရာ", "လုံခြုံရေးကင်မရာ"],
  ["မိုက်ခရို SD", "SIM ကတ်"],
  ["ဂရပ်ဖစ်ကတ်", "ပရိုဆက်ဆာ"],
  ["နောက်ကျခြင်း", "ဖိုင်တင်ချိန်ကြာခြင်း"],
  ["ဘက်ထရီချွေတာမုဒ်", "လေယာဉ်ပေါ်မုဒ်"],
  ["လှုပ်ရှား GIF", "ဗီဒီယိုတို"],
  ["အသံလျှော့စနစ်", "အသံပိတ်"],
  ["စမတ်တီဗီ", "ပရိုဂျက်တာ"],
  ["ဖိုင်ယာဝေါ", "စကားဝှက်မန်နေဂျာ"],
  ["QR ဖတ်စက်", "ဘာကုဒ်ဖတ်စက်"],
  ["ဗီဒီယိုတည်းဖြတ်စက်", "ဓာတ်ပုံတည်းဖြတ်စက်"],
  ["အလိုအလျောက်ဖုန်စုပ်စက်", "စမတ်စပီကာ"],
  ["ပလပ်အင်", "အပိုချဲ့ထွင်ချက်"],
  ["အခြေအနေမီး", "ညွှန်ပြမီး"],
  ["ရိုက်သံ", "ကလစ်သံ"],
])

const myanmarHardModePairs = pairs([
  ["ဗိုင်အိုလင်", "ဗီအိုလာ"],
  ["ပုတ်သင်ညို", "ဂက်ကို"],
  ["အိမ်ကြီး", "ဗီလာ"],
  ["မှတ်တမ်းစာအုပ်", "ဒိုင်ယာရီ"],
  ["ရုပ်တု", "ပန်းပု"],
  ["မီးပုံး", "မီးတိုင်"],
  ["ဟပ်", "လိုင်ယာ"],
  ["ရေမြောင်း", "မြစ်"],
  ["ကြယ်ပျံကျောက်ခဲ", "ကြယ်တံခွန်"],
  ["မှင်", "ဆေး"],
  ["နီလာ", "ပတ္တမြား"],
  ["ဖလူး", "ကလာရီနက်"],
  ["မှို", "ထရပ်ဖယ်"],
  ["လက်ရန်းအလှဆင်တန်း", "လက်ရန်း"],
  ["နားနေဆောင်", "ဂေဇီဘို"],
  ["ကွန်ပတ်", "ဆက်စတန်"],
  ["ဒေါ်ဖင်", "ပေါပိုက်စ်"],
  ["ဗယ်ဗက်", "ပိုးထည်"],
  ["ဟယ်လ်မက်", "လုပ်ငန်းခွင်ဦးထုပ်"],
  ["လက်ရေးမူ", "ဝတ္ထု"],
  ["လည်ဆွဲဖွင့်ပိတ်သေတ္တာ", "ဆွဲကြိုး"],
  ["လျှောက်လမ်းကြား", "လမ်းကြောင်း"],
  ["ချောက်ကမ်းပါးကြီး", "ကျောက်ချိုင့်"],
  ["ဟပ်စီကော့ဒ်", "စန္ဒယား"],
  ["ဘုန်းတော်ကြီးကျောင်း", "အဘေး"],
  ["ငှက်မုဆိုး", "လင်းယုန်"],
  ["ဂရန်နိုက်", "မားဘယ်"],
  ["နံရံချိတ်ယက်ထည်", "နံရံပန်းချီ"],
  ["စာရွက်ခပ်ဟောင်း", "ကန်ဗတ်"],
  ["လှံ", "ဂျာဗလင်"],
  ["ရာဇသင်္ကေတတံ", "မင်းဦးထုပ်"],
  ["ဆိပ်ကမ်း", "မာရီနာ"],
  ["တောင်ထိပ်", "အမြင့်ဆုံးနေရာ"],
  ["ပဲ့တင်သံ", "အသံပြန်"],
  ["ပတ်လမ်း", "လမ်းကြောင်း"],
  ["လဝက်ပုံ", "ကွေးဝိုင်း"],
  ["ပုံတူ", "ရင်ဘတ်ပန်းပု"],
  ["ငှက်မွေးကလံ", "သံချွန်ခေါင်း"],
  ["ကုန်သွားလာအုပ်စု", "ယာဉ်တန်း"],
  ["အရိပ်အယောင်ပုံ", "အပြင်လိုင်း"],
  ["အသံမြင့်လာမှု", "အထွတ်အထိပ်"],
  ["ကွန်ပတ်ပန်း", "မြေပုံအညွှန်း"],
  ["ဥပမာပုံပြင်", "ပုံပြင်တို"],
  ["မြေအောက်ခန်း", "သင်္ချိုင်းခန်း"],
  ["ကျောက်တုံးတစ်တုံး", "ကျောက်တိုင်"],
  ["လှံငါးဖမ်းတံ", "လှံ"],
  ["သစ်ခွ", "အိုင်ရစ်"],
  ["စိုစွတ်မြေ", "ရွှံ့မြေ"],
  ["धानဂိုဒေါင်", "စိုလို"],
  ["အိမ်အလယ်ဝင်း", "ဧည့်ခန်းမ"],
  ["ပန်းချီနံရံ", "မိုဇိတ်"],
  ["ယက်ကန်း", "လည်ပတ်ချည်တံ"],
  ["တန်ဒရာ", "မြက်ပြင်ကြီး"],
  ["ရေအိုင်", "လဂွန်း"],
  ["စာရင်းစာအုပ်", "မှတ်ပုံတင်စာရင်း"],
  ["ဆုတံဆိပ်", "ဒင်္ဂါး"],
  ["ကျီးကန်းမည်း", "ကျီးကန်း"],
  ["ဝတ်လုံ", "ကပ်"],
  ["ကျောက်စရစ်", "ကျောက်မှုန်"],
  ["ကျွန်းစု", "ကျွန်းဆွယ်"],
  ["မျှော်စင်ခေါင်း", "မျှော်စင်ငယ်"],
  ["ဆိပ်ကမ်းတာဝန်ခံ", "ကပ္ပတိန်"],
  ["မီးဖိုအောက်နေရာ", "မီးဖိုခေါင်းတန်း"],
  ["အဖုံးပါလသာဆောင်", "ဘော်လကနီ"],
  ["ပေါက်ကွဲချိုင့်", "အောက်ချိုင့်"],
  ["ညောင်ပင်", "သပိတ်ပင်"],
  ["ဖျော်ဒ်", "ပင်လယ်ကွေ့"],
  ["ဇယားကွက်တန်း", "လှည့်ကွက်တန်း"],
  ["သံတုံးတင်ခုံ", "မီးဖိုသံလုပ်ရုံ"],
  ["ကဗျာပိုဒ်", "ကဗျာကြောင်း"],
  ["စာရေးသမား", "စာရေးဆရာ"],
  ["မိုးကုပ်အမြင်", "မြင်ကွင်းကျယ်"],
  ["တိုင်", "ကော်လံ"],
  ["သစ်တောဝင်းလွင်", "အုပ်ပင်စု"],
  ["ကျောက်ပုံမှတ်တိုင်", "အထိမ်းအမှတ်ကျောက်တိုင်"],
  ["တောရှုပ်", "အကာပင်တန်း"],
  ["အရည်ထည့်ပစ္စည်း", "ဓာတ်ရည်ဘူး"],
  ["မီးကျန်အင်္ဂါ", "ပြာ"],
  ["ဝိုင်စည်", "စည်"],
  ["ကျောက်တန်း", "ရေတိမ်ကျောက်တန်း"],
  ["ပစ္စည်းသိုလှောင်သေတ္တာ", "သေတ္တာ"],
  ["တေးသမား", "ကဗျာတေးသမား"],
  ["လှေငယ်", "လှေသေး"],
  ["ပန်းချီတင်တိုင်", "တင်ခုံ"],
  ["ဓားလက်ကိုင်အကာ", "လက်ကိုင်"],
  ["ရှေးဟောင်းပစ္စည်း", "အမွေအနှစ်"],
  ["လိမ်ဝိုင်းပုံ", "ဟီလစ်စ်"],
  ["ဝက်သီး", "သစ်ချသီး"],
  ["လှိမ့်စာရွက်", "စာမူ"],
  ["ရေကြောင်းသား", "သင်္ဘောသား"],
  ["အလင်းဝင်ပေါက်", "လင့်စ်"],
  ["လက်ဆွဲအိတ်", "တုတ်အိတ်"],
  ["စာအုပ်ကြီး", "တွဲစာအုပ်"],
  ["သင်္ဘောကြီး", "တိုက်သင်္ဘော"],
  ["ခေါင်းလောင်းမျှော်စင်", "ခေါင်းလောင်းတိုင်"],
  ["စမ်းရေငယ်", "ချောင်းငယ်"],
  ["ရေဘူးခွက်", "ဖန်ရေဘူး"],
  ["ထုရေးပန်းချီ", "ခြစ်ရေးပန်းချီ"],
  ["မြို့ခံတပ်", "ခံတပ်"],
  ["မျက်နှာပြင်ပစ်မှတ်ညွှန်", "ချိန်ညှိပစ်မှတ်"],
])

const myanmarFamilyFunPairs = pairs([
  ["ကြောင်", "ခွေး"],
  ["ကိတ်", "ပိုင်"],
  ["မီးပုံးပျံ", "ရေပူဖောင်း"],
  ["ဘဲ", "ငန်း"],
  ["သက်တံ", "မိုးတိမ်"],
  ["ရုပ်စက်", "ကစားစရာကား"],
  ["ပင်လယ်ဓားပြ", "နင်ဂျာ"],
  ["ကွတ်ကီး", "ဘရောင်နီ"],
  ["ရဲတိုက်", "နန်းတော်"],
  ["ဝက်ဝံရုပ်", "အရုပ်မ"],
  ["ကြက်တူရွေး", "ဒေါင်း"],
  ["အာကာသယာဉ်", "ဒုံးပျံ"],
  ["သံပုရာရည်", "ဆိုဒါ"],
  ["ရတနာ", "မင်းဦးထုပ်"],
  ["ကရိုင်ယွန်", "မာကာ"],
  ["လှုပ်စီး", "လျှောစီး"],
  ["ခွေးကလေး", "ကြောင်ကလေး"],
  ["အိပ်ဝတ်", "စလစ်ပါ"],
  ["နဂါး", "ဒိုင်နိုဆော"],
  ["နှင်းလူ", "သဲရဲတိုက်"],
  ["မင်းသမီး", "နတ်သမီး"],
  ["သူရဲကောင်း", "မှော်ဆရာ"],
  ["ဂျယ်လီငါး", "ပင်လယ်ကြယ်"],
  ["ရေခဲချောင်း", "ရေခဲမုန့်"],
  ["မွေးနေ့", "ပွဲတော်နေ့"],
  ["ပဟေဠိ", "တုံးများ"],
  ["ဘောလုံးအိုင်", "ထရန်ပိုလင်း"],
  ["ယုန်", "ယုန်ကလေး"],
  ["မျောက်", "ဂေါ်ရီလာ"],
  ["ကစားစရာရထား", "ကစားစရာလေယာဉ်"],
  ["မီးသတ်ကား", "အရေးပေါ်လူနာတင်ကား"],
  ["သက်တံကိတ်", "ခွက်ကိတ်"],
  ["စတစ်ကာ", "တံဆိပ်တုံး"],
  ["တုတ်ခုန်ကစား", "လိုက်တမ်းကစား"],
  ["ရတနာမြေပုံ", "ပုံပြင်စာအုပ်"],
  ["ခဲတံအိတ်", "ကျောပိုးအိတ်"],
  ["ပန်းသီးရည်", "လိမ္မော်ရည်"],
  ["ဒိုင်နိုဆော", "နဂါး"],
  ["ယူနီကွန်", "ပျံမြင်း"],
  ["ရေချိုးကန်", "ရေကူးကန်"],
  ["ရဲတိုက်မျှော်စင်", "သစ်ပင်ပေါ်အိမ်"],
  ["ကစားစရာဒရမ်", "ကစားစရာစန္ဒယား"],
  ["ရွှေငါး", "လိပ်"],
  ["မီးပုံ", "ပျော်ပွဲစား"],
  ["မိုးဖိနပ်", "နှင်းဖိနပ်"],
  ["ယုန်နား", "ကြောင်နား"],
  ["ပလေးဒိုး", "ရွှံ့"],
  ["အရောင်ခြယ်စာအုပ်", "ကွန်မစ်စာအုပ်"],
  ["ကျောက်လုံး", "ဒိုင်စ်"],
  ["လော်လီပေါ့", "ဂမ်မီ"],
  ["ရတနာသေတ္တာ", "ကစားစရာပုံး"],
  ["စွန်", "စက္ကူလေယာဉ်"],
  ["ဒေစီပန်း", "နေကြာပန်း"],
  ["ချီတက်ပွဲ", "ပွဲတော်"],
  ["ပူပူနွေးနွေးကိုကိုး", "နို့ရည်"],
  ["ကလေးတွန်းလှည်း", "တွန်းလှည်းကား"],
  ["ပုန်းလျှိုးကွယ်လျှိုး", "ဖမ်းတမ်းကစား"],
  ["မင်းသား", "ဘုရင်"],
  ["ဘုရင်မ", "မင်းသမီး"],
  ["ပန်းပုရုပ်", "အရုပ်ကလေး"],
  ["ကစားကွင်း", "ပန်းခြံ"],
  ["အရုပ်ဆက်တင်", "ကစားမီးဖိုချောင်"],
  ["ရော်ဘာဘဲ", "ရေကစားလှေ"],
  ["သကြားလုံး", "ချောကလက်"],
  ["အရုပ်ဆရာဝန်ကိရိယာ", "အရုပ်ချက်ဖိုကိရိယာ"],
  ["ကစားစရာတံခါးခေါ်", "ကစားစရာဖုန်း"],
  ["ညအိပ်ပွဲ", "မွေးနေ့ပွဲ"],
  ["ပင်လယ်ကမ်းခြေဘောလုံး", "ဖောင်းဘောလုံး"],
  ["သဲပုံး", "ရေလောင်းဘူး"],
  ["ရုပ်ပြဇာတ်", "လက်အိတ်ရုပ်"],
  ["စတားပုံ", "နှလုံးပုံ"],
  ["ကစားစရာရေနွေးအိုး", "ကစားစရာခွက်"],
  ["ကစားစရာရဲကား", "ကစားစရာမီးသတ်ကား"],
  ["ကိတ်ဖယောင်းတိုင်", "မီးပုံးပျံကြိုး"],
  ["ကြိုးခုန်", "ဟူလာဟုပ်"],
  ["အရုပ်အိပ်ရာ", "အရုပ်စားပွဲ"],
  ["ရေချိုးပေါင်းဖော့", "ရေဖော့"],
  ["မျက်နှာဖုံး", "ဦးထုပ်"],
  ["သူရဲကောင်းအကာ", "မှော်တံ"],
  ["စကားပြောစာအုပ်", "ပုံပြင်ကတ်"],
  ["ချောကလက်နို့", "စတော်ဘယ်ရီနို့"],
  ["သစ်ပင်အိမ်", "တဲ"],
  ["ရေပေါက်သေနတ်", "ရေပုံး"],
  ["ကစားစရာငါးမျှားတံ", "လိပ်တံ"],
  ["ဆပ်ကပ်", "ပွဲတော်ခင်းကျင်းပွဲ"],
  ["တိရစ္ဆာန်ရုပ်", "လူရုပ်"],
  ["လက်သည်းကပ်စတစ်ကာ", "မျက်နှာပုံစတစ်ကာ"],
  ["ဆပ်ပြာပူဖောင်း", "ရေဖောင်းပူဖောင်း"],
  ["မိုးသီး", "နှင်းပွင့်"],
  ["ကစားစရာရေခဲမုန့်", "ကစားစရာကိတ်"],
  ["ကလေးဂီတသံ", "ခေါင်းလောင်းသံ"],
  ["သမုဒ္ဒရာပုံစာအုပ်", "တောပုံစာအုပ်"],
  ["သဲလွန်စလိုက်ဂိမ်း", "ရတနာလိုက်ရှာဂိမ်း"],
  ["ပန်းမန်ကလစ်", "တောက်ပကလစ်"],
  ["အနီရောင်ဖိနပ်", "အပြာရောင်ဖိနပ်"],
  ["ကျားရုပ်", "ခြင်္သေ့ရုပ်"],
  ["ကစားစရာဒုံးပျံ", "ကစားစရာအာကာသယာဉ်"],
  ["ကမ်းခြေပုံး", "ရေလောင်းဘူး"],
  ["ကစားစရာဖုန်း", "ကစားစရာကင်မရာ"],
  ["သက်တံလျှောစီး", "အဝိုင်းကြီးစီးစက်"],
  ["ကစားစရာဂေါ်ပြား", "ကစားစရာတုတ်လှည်း"],
])

export const wordPackLibrary: WordPackLibraryEntry[] = [
  {
    id: "classic",
    variants: {
      en: { name: "Classic", category: "General", pairs: classicPairs },
      my: { name: "Myanmar Classic", category: "Myanmar", pairs: myanmarClassicPairs },
    },
  },
  {
    id: "city-life",
    variants: {
      en: { name: "City Life", category: "Lifestyle", pairs: cityLifePairs },
      my: { name: "မြို့ပြဘဝ", category: "နေ့စဉ်ဘဝ", pairs: myanmarCityLifePairs },
    },
  },
  {
    id: "food-drink",
    variants: {
      en: { name: "Food & Drink", category: "Cuisine", pairs: foodDrinkPairs },
      my: { name: "အစားအသောက်", category: "စားသောက်မှု", pairs: myanmarFoodDrinkPairs },
    },
  },
  {
    id: "travel-nature",
    variants: {
      en: { name: "Travel & Nature", category: "Outdoors", pairs: travelNaturePairs },
      my: { name: "ခရီးသွား & သဘာဝ", category: "အပြင်ဘက်", pairs: myanmarTravelNaturePairs },
    },
  },
  {
    id: "tech-media",
    variants: {
      en: { name: "Tech & Media", category: "Technology", pairs: techMediaPairs },
      my: { name: "နည်းပညာ & မီဒီယာ", category: "နည်းပညာ", pairs: myanmarTechMediaPairs },
    },
  },
  {
    id: "sports-hobbies",
    variants: {
      en: { name: "Sports & Hobbies", category: "Play", pairs: sportsHobbiesPairs },
      my: { name: "အားကစား & ဝါသနာ", category: "ကစားမှု", pairs: myanmarSportsHobbiesPairs },
    },
  },
  {
    id: "school-work",
    variants: {
      en: { name: "School & Work", category: "Everyday", pairs: schoolWorkPairs },
      my: { name: "ကျောင်း & အလုပ်", category: "နေ့စဉ်", pairs: myanmarSchoolWorkPairs },
    },
  },
  {
    id: "home-daily",
    variants: {
      en: { name: "Home & Daily Life", category: "Home", pairs: homeDailyPairs },
      my: { name: "အိမ် & နေ့စဉ်ဘဝ", category: "အိမ်", pairs: myanmarHomeDailyPairs },
    },
  },
  {
    id: "hard-mode",
    variants: {
      en: { name: "Hard Mode", category: "Advanced", pairs: hardModePairs },
      my: { name: "ခက်ခဲမုဒ်", category: "အဆင့်မြင့်", pairs: myanmarHardModePairs },
    },
  },
  {
    id: "family-fun",
    variants: {
      en: { name: "Family Fun", category: "Family", pairs: familyFunPairs },
      my: { name: "မိသားစု ဖျော်ဖြေမှု", category: "မိသားစု", pairs: myanmarFamilyFunPairs },
    },
  },
]

const legacyPackAliases: Record<string, string> = {
  "myanmar-classic": "classic",
}

function normalizeLocale(locale?: string): SupportedWordLocale {
  return locale === "my" ? "my" : "en"
}

export function normalizeWordPackId(packId?: string): string {
  if (!packId) {
    return "classic"
  }

  return legacyPackAliases[packId] ?? packId
}

export function getDefaultWordPackId(locale = "en"): string {
  return normalizeLocale(locale) === "my" ? "classic" : "classic"
}

export function getWordPackLibraryEntry(packId?: string): WordPackLibraryEntry | undefined {
  const normalizedPackId = normalizeWordPackId(packId)
  return wordPackLibrary.find((entry) => entry.id === normalizedPackId)
}

export function isWordPackAvailableInLocale(packId: string, locale: string): boolean {
  const entry = getWordPackLibraryEntry(packId)
  const normalizedLocale = normalizeLocale(locale)
  return Boolean(entry?.variants[normalizedLocale])
}

export function listWordPacks(): WordPackSummary[] {
  return wordPackLibrary.map((entry) => {
    const availableLocales = Object.keys(entry.variants) as SupportedWordLocale[]
    const fallbackVariant = entry.variants.en ?? entry.variants[availableLocales[0]]

    return {
      id: entry.id,
      name: fallbackVariant?.name ?? entry.id,
      category: fallbackVariant?.category ?? "General",
      pairCount: fallbackVariant?.pairs.length ?? 0,
      availableLocales,
    }
  })
}

export const wordPacks: WordPackSummary[] = listWordPacks()

export function getWordPack(packId?: string, locale = "en"): WordPack {
  const normalizedLocale = normalizeLocale(locale)
  const defaultPackId = getDefaultWordPackId(normalizedLocale)
  const defaultEntry = getWordPackLibraryEntry(defaultPackId) ?? wordPackLibrary[0]
  const preferredEntry = getWordPackLibraryEntry(packId) ?? defaultEntry
  const preferredVariant = preferredEntry.variants[normalizedLocale]
  const fallbackVariant =
    defaultEntry.variants[normalizedLocale] ??
    preferredEntry.variants.en ??
    defaultEntry.variants.en
  const resolvedVariant = preferredVariant ?? fallbackVariant

  if (!resolvedVariant) {
    throw new Error(`No word pack variant available for pack "${preferredEntry.id}".`)
  }

  return {
    id: preferredVariant ? preferredEntry.id : defaultEntry.id,
    locale: preferredVariant
      ? normalizedLocale
      : normalizeLocale(defaultEntry.variants.my ? "my" : "en"),
    name: resolvedVariant.name,
    category: resolvedVariant.category,
    pairs: resolvedVariant.pairs,
  }
}
