export type WordPair = {
  civilian: string;
  undercover: string;
};

export type WordPack = {
  id: string;
  name: string;
  locale: string;
  category: string;
  pairs: WordPair[];
};

function pairs(entries: Array<[string, string]>): WordPair[] {
  return entries.map(([civilian, undercover]) => ({ civilian, undercover }));
}

const classicPairs = pairs([
  ["Coffee", "Tea"],
  ["Beach", "Desert"],
  ["Laptop", "Tablet"],
  ["Pizza", "Burger"],
  ["Thunder", "Lightning"],
  ["Forest", "Jungle"],
  ["Moon", "Sun"],
  ["River", "Lake"],
  ["Train", "Bus"],
  ["Snow", "Rain"],
  ["Window", "Mirror"],
  ["Soap", "Shampoo"],
  ["Pillow", "Blanket"],
  ["Spoon", "Fork"],
  ["Mountain", "Hill"],
  ["Bottle", "Cup"],
  ["Candle", "Lamp"],
  ["Clock", "Calendar"],
  ["Door", "Gate"],
  ["Apple", "Pear"],
  ["Chair", "Stool"],
  ["Shirt", "Jacket"],
  ["Bread", "Toast"],
  ["Ocean", "Sea"],
  ["Car", "Truck"],
  ["Hat", "Cap"],
  ["Ring", "Bracelet"],
  ["Fan", "Air conditioner"],
  ["Book", "Magazine"],
  ["Cake", "Pie"],
  ["Pen", "Pencil"],
  ["Road", "Highway"],
  ["Garden", "Park"],
  ["Bridge", "Tunnel"],
  ["Wallet", "Purse"],
  ["Scarf", "Tie"],
  ["Bell", "Horn"],
  ["Lantern", "Flashlight"],
  ["Socks", "Gloves"],
  ["Rope", "Chain"],
  ["Stone", "Brick"],
  ["Couch", "Bench"],
  ["Village", "Town"],
  ["Castle", "Fort"],
  ["Radio", "Speaker"],
  ["Helmet", "Mask"],
  ["Sugar", "Salt"],
  ["Duck", "Goose"],
  ["Nest", "Hive"],
  ["Seed", "Leaf"],
  ["Feather", "Fur"],
  ["Smile", "Laugh"],
  ["Pocket", "Bag"],
  ["Drawer", "Shelf"],
  ["Plate", "Bowl"],
  ["Map", "Compass"],
  ["Rocket", "Satellite"],
  ["Paint", "Ink"],
  ["Rug", "Mat"],
  ["Notebook", "Journal"],
  ["Boat", "Ship"],
  ["Fire", "Smoke"],
  ["Peach", "Plum"],
  ["Flower", "Rose"],
  ["Gold", "Silver"],
  ["Soup", "Sauce"],
  ["Bridge", "Viaduct"],
  ["Coin", "Token"],
  ["Shell", "Pearl"],
  ["Barn", "Shed"],
  ["Zoo", "Aquarium"],
  ["Ball", "Cube"],
  ["Spring", "Autumn"],
  ["Rabbit", "Squirrel"],
  ["Tiger", "Lion"],
  ["Lamp post", "Traffic light"],
  ["Chef", "Baker"],
  ["Soap bar", "Sponge"],
  ["Fountain", "Pond"],
  ["Tent", "Hammock"],
  ["Key", "Lock"],
  ["Passport", "Ticket"],
  ["Glasses", "Goggles"],
  ["Biscuit", "Cracker"],
  ["Sail", "Anchor"],
  ["Hammer", "Wrench"],
  ["Blank page", "Canvas"],
  ["Curtain", "Blinds"],
  ["Kite", "Balloon"],
  ["Rocket", "Missile"],
  ["Violin", "Cello"],
  ["Chocolate", "Candy"],
  ["Panda", "Koala"],
  ["Cave", "Tunnel"],
  ["Helmet", "Shield"],
  ["Recipe", "Menu"],
  ["Ladder", "Stairs"],
  ["Pineapple", "Coconut"],
  ["Crown", "Tiara"],
  ["Glove", "Mittens"]
]);

const cityLifePairs = pairs([
  ["Taxi", "Subway"],
  ["Balcony", "Rooftop"],
  ["Cinema", "Theater"],
  ["Backpack", "Briefcase"],
  ["Market", "Mall"],
  ["Crosswalk", "Intersection"],
  ["Apartment", "Condo"],
  ["Metro", "Tram"],
  ["Cafe", "Bakery"],
  ["Elevator", "Escalator"],
  ["Parking", "Garage"],
  ["Sidewalk", "Alley"],
  ["Office", "Studio"],
  ["Billboard", "Poster"],
  ["Helmet", "Seatbelt"],
  ["Doorman", "Guard"],
  ["Skyscraper", "Tower"],
  ["Food court", "Restaurant"],
  ["Scooter", "Bicycle"],
  ["Plaza", "Square"],
  ["Traffic jam", "Construction"],
  ["Streetlight", "Neon sign"],
  ["Food truck", "Street stall"],
  ["Bus stop", "Train station"],
  ["Condo lobby", "Hotel lobby"],
  ["Escalator", "Moving walkway"],
  ["Suburb", "Downtown"],
  ["Pedestrian", "Cyclist"],
  ["Subway map", "Transit card"],
  ["Mailroom", "Reception desk"],
  ["Bookstore", "Library"],
  ["Gym", "Pool"],
  ["Pharmacy", "Clinic"],
  ["Courier", "Postman"],
  ["Apartment key", "Keycard"],
  ["Window seat", "Aisle seat"],
  ["Street musician", "DJ"],
  ["Vendor", "Cashier"],
  ["Taxi stand", "Bus lane"],
  ["Newsstand", "Kiosk"],
  ["Bridge toll", "Parking meter"],
  ["Fire escape", "Emergency exit"],
  ["Rental bike", "Shared scooter"],
  ["Arcade", "Bowling alley"],
  ["Commuter", "Tourist"],
  ["Loft", "Penthouse"],
  ["Door buzzer", "Intercom"],
  ["Street fair", "Night market"],
  ["Street food", "Food hall"],
  ["Coffee cart", "Snack cart"],
  ["Studio apartment", "Dorm room"],
  ["Security camera", "Doorbell camera"],
  ["Street corner", "Intersection"],
  ["Taxi meter", "Fare gate"],
  ["Receptionist", "Concierge"],
  ["City bus", "Shuttle"],
  ["Rooftop bar", "Lounge"],
  ["Bike lane", "Sidewalk"],
  ["Turnstile", "Barrier"],
  ["Office badge", "Visitor pass"],
  ["Public square", "Courtyard"],
  ["Street mural", "Graffiti"],
  ["Coffee shop", "Tea house"],
  ["Parking lot", "Valet"],
  ["Daycare", "Preschool"],
  ["Neighborhood", "District"],
  ["Apartment hall", "Hotel corridor"],
  ["Trash chute", "Dumpster"],
  ["Delivery app", "Rideshare app"],
  ["Signal", "Crossing guard"],
  ["Skytrain", "Monorail"],
  ["Bus pass", "Train ticket"],
  ["Street cleaner", "Janitor"],
  ["Office cubicle", "Desk pod"],
  ["Plumber", "Electrician"],
  ["Streetlamp", "Headlight"],
  ["Restaurant menu", "QR menu"],
  ["Laundry shop", "Dry cleaner"],
  ["ATM", "Vending machine"],
  ["Food shelf", "Pantry"],
  ["Public bench", "Park bench"],
  ["Ride share", "Carpool"],
  ["Townhouse", "Row house"],
  ["Parking garage", "Basement lot"],
  ["Petrol station", "Charging station"],
  ["Bakery window", "Storefront"],
  ["Mall atrium", "Lobby"],
  ["Commuter train", "Express bus"],
  ["Union", "Guild"],
  ["Gym locker", "Storage locker"],
  ["Power line", "Telephone wire"],
  ["Stairwell", "Hallway"],
  ["Street vendor", "Shopkeeper"],
  ["Apartment rent", "Mortgage"],
  ["Street map", "Tour brochure"],
  ["Reception area", "Waiting room"],
  ["Public fountain", "Memorial"],
  ["Park gate", "Building gate"],
  ["Rooftop garden", "Courtyard garden"],
  ["Crosswalk button", "Doorbell"]
]);

const foodDrinkPairs = pairs([
  ["Pancake", "Waffle"],
  ["Noodles", "Pasta"],
  ["Taco", "Burrito"],
  ["Soup", "Stew"],
  ["Donut", "Bagel"],
  ["Cheese", "Butter"],
  ["Ketchup", "Salsa"],
  ["Lemon", "Lime"],
  ["Milkshake", "Smoothie"],
  ["Cookie", "Biscuit"],
  ["Muffin", "Cupcake"],
  ["Shrimp", "Crab"],
  ["Steak", "Ribs"],
  ["Rice", "Quinoa"],
  ["Bacon", "Ham"],
  ["Jam", "Honey"],
  ["Orange juice", "Apple juice"],
  ["Ice cream", "Frozen yogurt"],
  ["Sushi", "Sashimi"],
  ["Popcorn", "Nachos"],
  ["Latte", "Cappuccino"],
  ["Espresso", "Americano"],
  ["Pudding", "Custard"],
  ["Brownie", "Fudge"],
  ["Cereal", "Granola"],
  ["Porridge", "Oatmeal"],
  ["Pita", "Naan"],
  ["Toast", "Bagel"],
  ["Mango", "Peach"],
  ["Cherry", "Berry"],
  ["Watermelon", "Melon"],
  ["Curry", "Soup"],
  ["Dumpling", "Bao"],
  ["Croissant", "Pastry"],
  ["Pretzel", "Breadstick"],
  ["Mayonnaise", "Aioli"],
  ["Mustard", "Relish"],
  ["Hot dog", "Sausage"],
  ["Burger", "Sandwich"],
  ["Omelet", "Scramble"],
  ["Miso", "Broth"],
  ["Tortilla", "Wrap"],
  ["Chili", "Casserole"],
  ["Pickle", "Olive"],
  ["Mocha", "Hot chocolate"],
  ["Syrup", "Molasses"],
  ["Yogurt", "Pudding"],
  ["Cheesecake", "Tart"],
  ["Cup noodle", "Instant soup"],
  ["Lasagna", "Casserole"],
  ["Meatball", "Sausage"],
  ["Ramen", "Udon"],
  ["Gnocchi", "Dumpling"],
  ["Herb", "Spice"],
  ["Mint", "Basil"],
  ["Peanut butter", "Nutella"],
  ["Coconut milk", "Almond milk"],
  ["Sorbet", "Sherbet"],
  ["Jelly", "Jam"],
  ["Wonton", "Ravioli"],
  ["Kimchi", "Pickles"],
  ["Falafel", "Meatball"],
  ["Pesto", "Guacamole"],
  ["Baguette", "Ciabatta"],
  ["Pineapple pizza", "Ham pizza"],
  ["Cider", "Juice"],
  ["Lassi", "Smoothie"],
  ["Coconut water", "Sports drink"],
  ["Soda", "Sparkling water"],
  ["Tonic", "Seltzer"],
  ["Biscotti", "Cookie"],
  ["Macaron", "Meringue"],
  ["Scone", "Biscuit"],
  ["Caramel", "Toffee"],
  ["Hazelnut", "Almond"],
  ["Cashew", "Pistachio"],
  ["Tofu", "Paneer"],
  ["Edamame", "Peas"],
  ["Avocado", "Cucumber"],
  ["Cauliflower", "Broccoli"],
  ["Pumpkin", "Squash"],
  ["Chips", "Fries"],
  ["Kebab", "Skewer"],
  ["Pho", "Ramen"],
  ["Samosa", "Spring roll"],
  ["Croquette", "Nugget"],
  ["Salad", "Slaw"],
  ["Granita", "Sorbet"],
  ["Tea bag", "Coffee filter"],
  ["Margarita", "Daiquiri"],
  ["Cocoa", "Mocha"],
  ["Parfait", "Trifle"],
  ["Sea salt", "Rock salt"],
  ["Egg roll", "Burrito"],
  ["Tiramisu", "Cheesecake"],
  ["Pie crust", "Pastry shell"],
  ["Raisin", "Date"],
  ["Berry jam", "Fruit jelly"],
  ["Churro", "Donut"],
  ["Fried rice", "Paella"]
]);

const travelNaturePairs = pairs([
  ["Island", "Peninsula"],
  ["Waterfall", "Fountain"],
  ["Tent", "Cabin"],
  ["Passport", "Visa"],
  ["Suitcase", "Duffel bag"],
  ["Campfire", "Fireplace"],
  ["Glacier", "Iceberg"],
  ["Volcano", "Geyser"],
  ["Trail", "Route"],
  ["Safari", "Zoo"],
  ["Map", "Compass"],
  ["Kayak", "Canoe"],
  ["Cabin crew", "Pilot"],
  ["Airbnb", "Hotel"],
  ["Harbor", "Dock"],
  ["Coral reef", "Seaweed"],
  ["Rainbow", "Sunset"],
  ["Pine tree", "Palm tree"],
  ["Motel", "Hostel"],
  ["Hiking boots", "Snow boots"],
  ["Lagoon", "Bay"],
  ["Canyon", "Valley"],
  ["Ridge", "Cliff"],
  ["Dune", "Hill"],
  ["Pebble", "Shell"],
  ["Harbor cruise", "Ferry"],
  ["Boarding pass", "Ticket"],
  ["Camp site", "Picnic site"],
  ["Peak", "Summit"],
  ["Fog", "Mist"],
  ["Rainforest", "Wetland"],
  ["Cave", "Cavern"],
  ["Meadow", "Field"],
  ["Cabin trail", "Forest path"],
  ["Riverbank", "Shoreline"],
  ["Whale", "Dolphin"],
  ["Seal", "Otter"],
  ["Pond", "Creek"],
  ["Berry bush", "Vine"],
  ["Palm grove", "Forest"],
  ["Water bottle", "Canteen"],
  ["Backpacker", "Camper"],
  ["Sunrise", "Dawn"],
  ["Twilight", "Dusk"],
  ["Desert camp", "Mountain lodge"],
  ["Tide", "Wave"],
  ["Anchor", "Rudder"],
  ["Trailhead", "Checkpoint"],
  ["Snowfall", "Avalanche"],
  ["Wildflower", "Fern"],
  ["Boardwalk", "Pier"],
  ["Travel pillow", "Neck pillow"],
  ["Binoculars", "Telescope"],
  ["Trail mix", "Granola bar"],
  ["Gate", "Terminal"],
  ["Boarding line", "Security line"],
  ["Travel guide", "Map book"],
  ["Beach towel", "Picnic blanket"],
  ["Lifeboat", "Raft"],
  ["Paddles", "Oars"],
  ["Jet lag", "Motion sickness"],
  ["Mountain cabin", "Beach hut"],
  ["Jacket", "Raincoat"],
  ["Horizon", "Skyline"],
  ["Campsite", "Basecamp"],
  ["Lantern", "Camp light"],
  ["Mosquito", "Bee"],
  ["Trail sign", "Road sign"],
  ["Border", "Customs"],
  ["Ski lift", "Cable car"],
  ["Tundra", "Prairie"],
  ["Water bottle", "Thermos"],
  ["Tent peg", "Rope stake"],
  ["Postcard", "Souvenir"],
  ["Museum", "Monument"],
  ["Ruins", "Temple"],
  ["National park", "Botanical garden"],
  ["Rope bridge", "Suspension bridge"],
  ["Bird nest", "Burrow"],
  ["Coconut tree", "Banana tree"],
  ["Hammock", "Beach chair"],
  ["Rain jacket", "Poncho"],
  ["Camp stove", "Grill"],
  ["Picnic basket", "Cooler"],
  ["Lighthouse", "Beacon"],
  ["Turtle", "Tortoise"],
  ["Penguin", "Seagull"],
  ["Cabin window", "Porthole"],
  ["Stargazing", "Birdwatching"],
  ["Orchid", "Lily"],
  ["Moss", "Lichen"],
  ["Dirt road", "Gravel road"],
  ["Trail marker", "Milestone"],
  ["Sea breeze", "Mountain air"],
  ["Tour bus", "Shuttle"],
  ["Wave pool", "Lagoon"],
  ["Camp chair", "Beach stool"],
  ["Travel pouch", "Passport holder"],
  ["Forest cabin", "Lake house"],
  ["River ferry", "Speedboat"]
]);

const techMediaPairs = pairs([
  ["Keyboard", "Piano"],
  ["Headphones", "Earbuds"],
  ["Charger", "Adapter"],
  ["Streaming", "Broadcast"],
  ["Podcast", "Radio"],
  ["Camera", "Camcorder"],
  ["Microphone", "Speaker"],
  ["Mouse", "Trackpad"],
  ["Password", "PIN"],
  ["Browser", "Search engine"],
  ["App", "Website"],
  ["Notification", "Alarm"],
  ["Drone", "Helicopter"],
  ["Projector", "Monitor"],
  ["Battery", "Generator"],
  ["Cloud", "Server"],
  ["Screenshot", "Photo"],
  ["Joystick", "Controller"],
  ["Printer", "Scanner"],
  ["Playlist", "Album"],
  ["Tablet", "E-reader"],
  ["Router", "Modem"],
  ["Hard drive", "USB drive"],
  ["Upload", "Download"],
  ["Emoji", "Sticker"],
  ["Avatar", "Profile picture"],
  ["Keyboard shortcut", "Macro"],
  ["Filter", "Lens"],
  ["Tripod", "Stand"],
  ["Live stream", "Video call"],
  ["Text message", "Email"],
  ["Watch", "Smartwatch"],
  ["Console", "PC"],
  ["Laptop stand", "Monitor arm"],
  ["Firewall", "Antivirus"],
  ["Browser tab", "Window"],
  ["Bookmark", "Favorite"],
  ["Search bar", "Address bar"],
  ["Podcast episode", "Radio segment"],
  ["Playlist cover", "Album art"],
  ["VR headset", "Helmet"],
  ["Smart speaker", "Voice assistant"],
  ["Remote", "Gamepad"],
  ["Keyboard backlight", "Screen brightness"],
  ["Data cable", "Power cable"],
  ["Proxy", "VPN"],
  ["User name", "Handle"],
  ["Cloud backup", "Archive"],
  ["Folder", "Directory"],
  ["Cursor", "Pointer"],
  ["Code editor", "Terminal"],
  ["Bug", "Glitch"],
  ["Patch", "Update"],
  ["Beta", "Demo"],
  ["Thumbnail", "Poster"],
  ["Livestream chat", "Comment section"],
  ["Notification badge", "Alert icon"],
  ["Chat bot", "Moderator"],
  ["Wireless mouse", "Bluetooth speaker"],
  ["Touchscreen", "Trackpad"],
  ["Camera roll", "Gallery"],
  ["Headset mic", "Boom mic"],
  ["Streaming app", "Video app"],
  ["Voice memo", "Audio note"],
  ["Ring light", "Desk lamp"],
  ["Charger brick", "Power bank"],
  ["Mirrorless", "DSLR"],
  ["Microchip", "Circuit board"],
  ["Operating system", "Software"],
  ["Software", "Firmware"],
  ["Link", "QR code"],
  ["Screen share", "Projector mode"],
  ["Notification sound", "Ringtone"],
  ["Podcast host", "Radio host"],
  ["Cloud storage", "External drive"],
  ["Edit", "Crop"],
  ["Photo filter", "Video effect"],
  ["USB port", "HDMI port"],
  ["Coding", "Scripting"],
  ["Server rack", "Desktop tower"],
  ["Monitor stand", "Docking station"],
  ["Control room", "Studio"],
  ["Caption", "Subtitle"],
  ["Touch ID", "Face ID"],
  ["Dark mode", "Night light"],
  ["Webcam", "Security camera"],
  ["Micro SD", "SIM card"],
  ["Graphics card", "Processor"],
  ["Lag", "Buffering"],
  ["Battery saver", "Airplane mode"],
  ["Animated GIF", "Short video"],
  ["Noise canceling", "Mute"],
  ["Smart TV", "Projector"],
  ["Firewall", "Password manager"],
  ["QR scanner", "Barcode scanner"],
  ["Video editor", "Photo editor"],
  ["Robot vacuum", "Smart speaker"],
  ["Plug-in", "Extension"],
  ["Status light", "Indicator light"],
  ["Typing sound", "Click sound"]
]);

const sportsHobbiesPairs = pairs([
  ["Football", "Rugby"],
  ["Tennis", "Badminton"],
  ["Swimming", "Diving"],
  ["Chess", "Checkers"],
  ["Painting", "Drawing"],
  ["Guitar", "Ukulele"],
  ["Drums", "Tambourine"],
  ["Basketball", "Volleyball"],
  ["Skateboard", "Surfboard"],
  ["Fishing", "Hunting"],
  ["Bowling", "Darts"],
  ["Yoga", "Pilates"],
  ["Origami", "Knitting"],
  ["Karaoke", "Concert"],
  ["Puzzle", "Riddle"],
  ["Snowboard", "Ski"],
  ["Baseball", "Cricket"],
  ["Boxing", "Wrestling"],
  ["Ballet", "Gymnastics"],
  ["Comic book", "Manga"],
  ["Soccer", "Futsal"],
  ["Marathon", "Sprint"],
  ["Cycling", "Running"],
  ["Golf", "Mini golf"],
  ["Dribbling", "Passing"],
  ["Climbing", "Hiking"],
  ["Snorkeling", "Scuba"],
  ["Pottery", "Ceramics"],
  ["Calligraphy", "Lettering"],
  ["Crochet", "Sewing"],
  ["Piano", "Keyboard"],
  ["Flute", "Recorder"],
  ["Violin", "Cello"],
  ["Acting", "Improv"],
  ["Juggling", "Magic"],
  ["Card trick", "Puzzle trick"],
  ["Camping", "Backpacking"],
  ["Birdwatching", "Stargazing"],
  ["Archery", "Darts"],
  ["Karate", "Taekwondo"],
  ["Fencing", "Kendo"],
  ["Board game", "Card game"],
  ["Sudoku", "Crossword"],
  ["Clay", "Slime"],
  ["Photography", "Filming"],
  ["Collecting stamps", "Collecting coins"],
  ["Model train", "RC car"],
  ["RC plane", "Drone"],
  ["Surfing", "Wakeboarding"],
  ["Roller skating", "Ice skating"],
  ["Long jump", "High jump"],
  ["Shot put", "Discus"],
  ["Table tennis", "Air hockey"],
  ["Billiards", "Snooker"],
  ["Choir", "Band"],
  ["Songwriting", "Poetry"],
  ["Reading club", "Debate club"],
  ["Cosplay", "Costume design"],
  ["Baking", "Cooking"],
  ["Fishing rod", "Net"],
  ["Camping stove", "Portable grill"],
  ["Kite flying", "Paper plane"],
  ["Puzzle cube", "Jigsaw"],
  ["Base jump", "Bungee jump"],
  ["Bodybuilding", "Powerlifting"],
  ["Bench press", "Deadlift"],
  ["Ice hockey", "Field hockey"],
  ["Handball", "Netball"],
  ["Rowing", "Canoeing"],
  ["Sailing", "Windsurfing"],
  ["Horse riding", "Camel riding"],
  ["Dog agility", "Horse jumping"],
  ["Magic card", "Playing card"],
  ["Lego build", "Model kit"],
  ["Embroidery", "Cross-stitch"],
  ["Whittling", "Wood carving"],
  ["Hip hop", "Breakdance"],
  ["Salsa", "Tango"],
  ["Meditation", "Breathing exercise"],
  ["Field trip", "Camping trip"],
  ["Film club", "Drama club"],
  ["Trivia night", "Quiz show"],
  ["Escape room", "Treasure hunt"],
  ["Treasure map", "Clue sheet"],
  ["Sledding", "Tubing"],
  ["Parkour", "Gymnastics"],
  ["Miniature painting", "Sketching"],
  ["Aquarium keeping", "Gardening"],
  ["Flower arranging", "Table setting"],
  ["Snow angel", "Sand angel"],
  ["Ping pong paddle", "Tennis racket"],
  ["Goalkeeper", "Defender"],
  ["Referee", "Coach"],
  ["Scoreboard", "Stopwatch"],
  ["Team captain", "Club president"],
  ["Cheerleading", "Dance team"],
  ["Costume", "Uniform"],
  ["Croquet", "Bocce"],
  ["Foam roller", "Yoga mat"],
  ["Sketchbook", "Canvas pad"]
]);

const schoolWorkPairs = pairs([
  ["Teacher", "Professor"],
  ["Homework", "Quiz"],
  ["Notebook", "Textbook"],
  ["Stapler", "Paperclip"],
  ["Whiteboard", "Blackboard"],
  ["Intern", "Assistant"],
  ["Meeting", "Workshop"],
  ["Resume", "Portfolio"],
  ["Deadline", "Schedule"],
  ["Presentation", "Lecture"],
  ["Manager", "Supervisor"],
  ["Uniform", "Dress code"],
  ["Calculator", "Abacus"],
  ["Locker", "Drawer"],
  ["Bell", "Whistle"],
  ["Marker", "Crayon"],
  ["Clipboard", "Folder"],
  ["Exam", "Interview"],
  ["Lab", "Workshop"],
  ["Certificate", "Diploma"],
  ["Principal", "Dean"],
  ["Classroom", "Lecture hall"],
  ["Desk", "Cubicle"],
  ["Hall pass", "Visitor pass"],
  ["Essay", "Report"],
  ["Syllabus", "Agenda"],
  ["Lesson", "Tutorial"],
  ["Mentor", "Tutor"],
  ["Internship", "Apprenticeship"],
  ["Payroll", "Invoice"],
  ["Memo", "Notice"],
  ["Orientation", "Onboarding"],
  ["Name tag", "Badge"],
  ["Attendance", "Timesheet"],
  ["Shift", "Schedule"],
  ["Reception", "Front desk"],
  ["Staff room", "Break room"],
  ["Locker room", "Storage room"],
  ["Project", "Assignment"],
  ["Planner", "Calendar"],
  ["Notebook paper", "Sticky note"],
  ["Photocopier", "Printer"],
  ["Projector screen", "Whiteboard"],
  ["Brainstorm", "Discussion"],
  ["Manager meeting", "Team huddle"],
  ["Payroll", "Budget"],
  ["Grade", "Score"],
  ["Uniform shirt", "Name badge"],
  ["Spreadsheet", "Report"],
  ["Desk lamp", "Monitor light"],
  ["Calculator app", "Spreadsheet"],
  ["Signature", "Initials"],
  ["Research", "Survey"],
  ["Experiment", "Observation"],
  ["Assignment sheet", "Rubric"],
  ["Group project", "Case study"],
  ["Attendance sheet", "Roster"],
  ["Career fair", "Open house"],
  ["Training", "Seminar"],
  ["Orientation week", "Exam week"],
  ["Office chair", "Desk chair"],
  ["Cubicle wall", "Whiteboard wall"],
  ["Textbook chapter", "Workbook page"],
  ["Planner app", "Calendar app"],
  ["Memo pad", "Notebook"],
  ["Report card", "Transcript"],
  ["Reference letter", "Certificate"],
  ["Phone interview", "Video interview"],
  ["Course", "Class"],
  ["Major", "Minor"],
  ["Field trip", "Lab visit"],
  ["Faculty", "Department"],
  ["Notebook tab", "Binder tab"],
  ["Paper tray", "Mailbox"],
  ["Janitor closet", "Supply room"],
  ["Cafeteria", "Food court"],
  ["Auditorium", "Gymnasium"],
  ["Semester", "Quarter"],
  ["Payroll stub", "Receipt"],
  ["Company policy", "Rulebook"],
  ["Team lead", "Supervisor"],
  ["School bus", "Shuttle"],
  ["Class photo", "ID photo"],
  ["Poster board", "Tri-fold board"],
  ["Science fair", "Book fair"],
  ["Craft paper", "Printer paper"],
  ["Timer", "Stopwatch"],
  ["Reception call", "Help desk ticket"],
  ["Checklist", "Worksheet"],
  ["Q and A", "Discussion"],
  ["Revision", "Draft"],
  ["Coach", "Advisor"],
  ["Shift manager", "Floor manager"],
  ["Office lunch", "School lunch"],
  ["Transcript", "Resume"],
  ["Planner sticker", "Sticky note"],
  ["Homework folder", "Lunch box"],
  ["Company email", "Memo"],
  ["Desk organizer", "Supply tray"],
  ["Workshop room", "Conference room"]
]);

const homeDailyPairs = pairs([
  ["Sofa", "Armchair"],
  ["Fridge", "Freezer"],
  ["Toothbrush", "Razor"],
  ["Laundry", "Dishes"],
  ["Broom", "Mop"],
  ["Curtain", "Blinds"],
  ["Pan", "Pot"],
  ["Closet", "Wardrobe"],
  ["Alarm clock", "Timer"],
  ["Toaster", "Microwave"],
  ["Sink", "Bathtub"],
  ["Vacuum", "Leaf blower"],
  ["Hanger", "Hook"],
  ["Rug", "Carpet"],
  ["Nightstand", "Desk"],
  ["Shower", "Faucet"],
  ["Soap dispenser", "Lotion bottle"],
  ["Couch", "Bench"],
  ["Kettle", "Teapot"],
  ["Mailbox", "Package box"],
  ["Dish rack", "Drying rack"],
  ["Laundry basket", "Storage bin"],
  ["Pillowcase", "Bedsheet"],
  ["Mattress", "Futon"],
  ["Blanket", "Comforter"],
  ["Curtain rod", "Shelf bracket"],
  ["Remote", "Switch"],
  ["Ceiling fan", "Table fan"],
  ["Doormat", "Bath mat"],
  ["Door handle", "Cabinet knob"],
  ["Stove", "Oven"],
  ["Frying pan", "Saucepan"],
  ["Knife", "Scissors"],
  ["Plate rack", "Cup shelf"],
  ["Dining table", "Coffee table"],
  ["Laundry detergent", "Fabric softener"],
  ["Iron", "Steamer"],
  ["Basket", "Bucket"],
  ["Dustpan", "Brush"],
  ["Shampoo bottle", "Conditioner bottle"],
  ["Toilet paper", "Paper towel"],
  ["Bath towel", "Hand towel"],
  ["Mug", "Glass"],
  ["Blender", "Mixer"],
  ["Rice cooker", "Slow cooker"],
  ["Dish sponge", "Scrub brush"],
  ["Laundry room", "Pantry"],
  ["Trash can", "Recycling bin"],
  ["Bed frame", "Headboard"],
  ["Mirror cabinet", "Medicine cabinet"],
  ["Shoe rack", "Coat rack"],
  ["Vacuum bag", "Trash bag"],
  ["Cushion", "Pillow"],
  ["Shelf", "Cabinet"],
  ["Desk lamp", "Floor lamp"],
  ["Light switch", "Doorbell"],
  ["Freezer tray", "Ice bucket"],
  ["Soap bar", "Shower gel"],
  ["Washing machine", "Dryer"],
  ["Laundry line", "Clothes rack"],
  ["Bathroom sink", "Kitchen sink"],
  ["Water jug", "Pitcher"],
  ["Dishwasher", "Drying rack"],
  ["Apron", "Oven mitt"],
  ["Clock radio", "Alarm clock"],
  ["Tea towel", "Napkin"],
  ["Storage box", "Drawer organizer"],
  ["Vacuum hose", "Garden hose"],
  ["Wall shelf", "Bookcase"],
  ["Bedroom", "Guest room"],
  ["Dining chair", "Bar stool"],
  ["Soap tray", "Toothbrush holder"],
  ["Tissue box", "Wipes box"],
  ["Window sill", "Door frame"],
  ["Pan lid", "Pot lid"],
  ["Water filter", "Kettle"],
  ["Bedside lamp", "Hall lamp"],
  ["Bathrobe", "Pajamas"],
  ["Laundry soap", "Dish soap"],
  ["Cleaning spray", "Air freshener"],
  ["Cupboard", "Pantry"],
  ["Toilet brush", "Bottle brush"],
  ["Mixer bowl", "Salad bowl"],
  ["Spice rack", "Knife block"],
  ["Linen closet", "Pantry closet"],
  ["House key", "Mailbox key"],
  ["Pet bed", "Baby crib"],
  ["Laundry hamper", "Toy basket"],
  ["Blanket ladder", "Towel rack"],
  ["Watering can", "Spray bottle"],
  ["Drain", "Plug"],
  ["Rolling pin", "Whisk"],
  ["Measuring cup", "Measuring spoon"],
  ["Clock battery", "Remote battery"],
  ["Shower curtain", "Glass door"],
  ["Paper lantern", "Ceiling lamp"],
  ["Laundry clips", "Hangers"],
  ["Kitchen timer", "Egg timer"],
  ["Porch", "Patio"],
  ["Entryway", "Hallway"]
]);

const hardModePairs = pairs([
  ["Violin", "Viola"],
  ["Lizard", "Gecko"],
  ["Mansion", "Villa"],
  ["Journal", "Diary"],
  ["Statue", "Sculpture"],
  ["Lantern", "Torch"],
  ["Harp", "Lyre"],
  ["Canal", "River"],
  ["Meteor", "Comet"],
  ["Ink", "Paint"],
  ["Sapphire", "Ruby"],
  ["Flute", "Clarinet"],
  ["Mushroom", "Truffle"],
  ["Balustrade", "Railing"],
  ["Pavilion", "Gazebo"],
  ["Compass", "Sextant"],
  ["Dolphin", "Porpoise"],
  ["Velvet", "Silk"],
  ["Helmet", "Hard hat"],
  ["Manuscript", "Novel"],
  ["Locket", "Pendant"],
  ["Aisle", "Corridor"],
  ["Chasm", "Canyon"],
  ["Harpsichord", "Piano"],
  ["Monastery", "Abbey"],
  ["Falcon", "Hawk"],
  ["Granite", "Marble"],
  ["Tapestry", "Mural"],
  ["Parchment", "Canvas"],
  ["Spear", "Javelin"],
  ["Scepter", "Crown"],
  ["Harbor", "Marina"],
  ["Summit", "Peak"],
  ["Echo", "Reverb"],
  ["Orbit", "Trajectory"],
  ["Crescent", "Arc"],
  ["Portrait", "Bust"],
  ["Quill", "Nib"],
  ["Caravan", "Convoy"],
  ["Silhouette", "Outline"],
  ["Crescendo", "Climax"],
  ["Compass rose", "Map legend"],
  ["Parable", "Fable"],
  ["Vault", "Crypt"],
  ["Monolith", "Obelisk"],
  ["Harpoon", "Spear"],
  ["Orchid", "Iris"],
  ["Marsh", "Bog"],
  ["Granary", "Silo"],
  ["Atrium", "Foyer"],
  ["Fresco", "Mosaic"],
  ["Loom", "Spindle"],
  ["Tundra", "Steppe"],
  ["Pond", "Lagoon"],
  ["Ledger", "Register"],
  ["Medallion", "Coin"],
  ["Raven", "Crow"],
  ["Cloak", "Cape"],
  ["Pebble", "Gravel"],
  ["Archipelago", "Peninsula"],
  ["Spire", "Turret"],
  ["Harbor master", "Captain"],
  ["Hearth", "Mantel"],
  ["Lanai", "Balcony"],
  ["Crater", "Basin"],
  ["Banyan", "Oak"],
  ["Fjord", "Bay"],
  ["Lattice", "Trellis"],
  ["Anvil", "Forge"],
  ["Stanza", "Verse"],
  ["Scribe", "Author"],
  ["Horizon", "Vista"],
  ["Pillar", "Column"],
  ["Glade", "Grove"],
  ["Cairn", "Monument"],
  ["Thicket", "Hedge"],
  ["Vessel", "Flask"],
  ["Ember", "Ash"],
  ["Cask", "Barrel"],
  ["Reef", "Shoal"],
  ["Coffer", "Chest"],
  ["Minstrel", "Bard"],
  ["Skiff", "Dinghy"],
  ["Easel", "Stand"],
  ["Hilt", "Handle"],
  ["Relic", "Artifact"],
  ["Spiral", "Helix"],
  ["Acorn", "Chestnut"],
  ["Scroll", "Script"],
  ["Mariner", "Sailor"],
  ["Aperture", "Lens"],
  ["Satchel", "Tote"],
  ["Tome", "Volume"],
  ["Galleon", "Frigate"],
  ["Belfry", "Bell tower"],
  ["Rivulet", "Stream"],
  ["Carafe", "Decanter"],
  ["Etching", "Engraving"],
  ["Citadel", "Fortress"],
  ["Reticle", "Crosshair"]
]);

const familyFunPairs = pairs([
  ["Cat", "Dog"],
  ["Cake", "Pie"],
  ["Balloon", "Bubble"],
  ["Duck", "Goose"],
  ["Rainbow", "Cloud"],
  ["Robot", "Toy car"],
  ["Pirate", "Ninja"],
  ["Cookie", "Brownie"],
  ["Castle", "Palace"],
  ["Teddy bear", "Doll"],
  ["Parrot", "Peacock"],
  ["Spaceship", "Rocket"],
  ["Lemonade", "Soda"],
  ["Treasure", "Crown"],
  ["Crayon", "Marker"],
  ["Swing", "Slide"],
  ["Puppy", "Kitten"],
  ["Pajamas", "Slippers"],
  ["Dragon", "Dinosaur"],
  ["Snowman", "Sandcastle"],
  ["Princess", "Fairy"],
  ["Knight", "Wizard"],
  ["Jellyfish", "Starfish"],
  ["Popsicle", "Ice cream"],
  ["Birthday", "Holiday"],
  ["Puzzle", "Blocks"],
  ["Ball pit", "Trampoline"],
  ["Rabbit", "Bunny"],
  ["Monkey", "Gorilla"],
  ["Toy train", "Toy plane"],
  ["Fire truck", "Ambulance"],
  ["Rainbow cake", "Cupcake"],
  ["Sticker", "Stamp"],
  ["Hopscotch", "Tag"],
  ["Treasure map", "Storybook"],
  ["Pencil case", "Backpack"],
  ["Apple juice", "Orange juice"],
  ["Dinosaur", "Dragon"],
  ["Unicorn", "Pegasus"],
  ["Bathtub", "Pool"],
  ["Castle tower", "Treehouse"],
  ["Toy drum", "Toy piano"],
  ["Goldfish", "Turtle"],
  ["Campfire", "Picnic"],
  ["Rain boots", "Snow boots"],
  ["Bunny ears", "Cat ears"],
  ["Playdough", "Clay"],
  ["Coloring book", "Comic book"],
  ["Marble", "Dice"],
  ["Lollipop", "Gummy"],
  ["Treasure chest", "Toy box"],
  ["Kite", "Paper plane"],
  ["Daisy", "Sunflower"],
  ["Parade", "Festival"],
  ["Storybook", "Fairy tale"],
  ["Cookie jar", "Candy jar"],
  ["Pond", "Puddle"],
  ["Bicycle", "Scooter"],
  ["Toy soldier", "Action figure"],
  ["Water gun", "Bubble wand"],
  ["Jungle gym", "Monkey bars"],
  ["Hide and seek", "Tag"],
  ["Ring toss", "Bowling"],
  ["Puppet", "Plushie"],
  ["Pony", "Horse"],
  ["Duck pond", "Fish pond"],
  ["Moon", "Star"],
  ["Birthday hat", "Party mask"],
  ["Crown", "Tiara"],
  ["Cookie cutter", "Rolling pin"],
  ["Bedtime story", "Lullaby"],
  ["Blanket fort", "Treehouse"],
  ["Treasure hunt", "Scavenger hunt"],
  ["Toy chef", "Toy doctor"],
  ["Tugboat", "Sailboat"],
  ["Beach ball", "Soccer ball"],
  ["Spring roll", "Rice ball"],
  ["Piggy bank", "Treasure chest"],
  ["Shark", "Whale"],
  ["Cloud", "Fog"],
  ["Magic wand", "Sword"],
  ["Knight helmet", "Pirate hat"],
  ["Rubber duck", "Toy boat"],
  ["Toy kitchen", "Toy store"],
  ["Color pencil", "Crayon"],
  ["Fruit snack", "Granola bar"],
  ["Popsicle stick", "Straw"],
  ["Dress-up", "Costume party"],
  ["Snowflake", "Raindrop"],
  ["Playhouse", "Clubhouse"],
  ["Bunny hop", "Frog jump"],
  ["Firefly", "Butterfly"],
  ["Pine cone", "Acorn"],
  ["Cracker", "Pretzel"],
  ["Sled", "Wagon"],
  ["Toy rocket", "Toy spaceship"],
  ["Beach bucket", "Watering can"],
  ["Toy phone", "Toy camera"],
  ["Rainbow slide", "Ferris wheel"],
  ["Toy shovel", "Toy rake"]
]);

export const wordPacks: WordPack[] = [
  { id: "classic", name: "Classic", locale: "en", category: "General", pairs: classicPairs },
  { id: "city-life", name: "City Life", locale: "en", category: "Lifestyle", pairs: cityLifePairs },
  { id: "food-drink", name: "Food & Drink", locale: "en", category: "Cuisine", pairs: foodDrinkPairs },
  { id: "travel-nature", name: "Travel & Nature", locale: "en", category: "Outdoors", pairs: travelNaturePairs },
  { id: "tech-media", name: "Tech & Media", locale: "en", category: "Technology", pairs: techMediaPairs },
  { id: "sports-hobbies", name: "Sports & Hobbies", locale: "en", category: "Play", pairs: sportsHobbiesPairs },
  { id: "school-work", name: "School & Work", locale: "en", category: "Everyday", pairs: schoolWorkPairs },
  { id: "home-daily", name: "Home & Daily Life", locale: "en", category: "Home", pairs: homeDailyPairs },
  { id: "hard-mode", name: "Hard Mode", locale: "en", category: "Advanced", pairs: hardModePairs },
  { id: "family-fun", name: "Family Fun", locale: "en", category: "Family", pairs: familyFunPairs }
];

export function getWordPack(packId?: string): WordPack {
  if (!packId) {
    return wordPacks[0];
  }

  return wordPacks.find((pack) => pack.id === packId) ?? wordPacks[0];
}
